// Concatenate host/index.jsfl + host/runner-main.jsfl into a single
// self-contained host/cf7ak-runner.jsfl that Animate can run directly
// (Animate.exe cf7ak-runner.jsfl) — the headless cf7ak job runner.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const hostDir = path.join(here, '..', 'host');

const index = fs.readFileSync(path.join(hostDir, 'index.jsfl'), 'utf8');
const runner = fs.readFileSync(path.join(hostDir, 'runner-main.jsfl'), 'utf8');

const banner =
  '// GENERATED by build-runner.mjs — DO NOT EDIT. Source: index.jsfl + runner-main.jsfl\n' +
  '// Self-contained headless cf7ak runner. Pass to Animate: Animate.exe cf7ak-runner.jsfl\n\n';

const out = `${banner}${index}\n\n// ---- runner main ----\n${runner}`;
const outPath = path.join(hostDir, 'cf7ak-runner.jsfl');
fs.writeFileSync(outPath, out, 'utf8');
console.log(`[build-runner] wrote ${outPath} (${out.length} bytes)`);
