// Generated by tools/generate-scene-transition-catalog.js.
using System.Collections.Generic;
namespace CF7Launcher.Tasks {
    internal static class SceneTransitionCatalog {
        internal static readonly IReadOnlyDictionary<string,string> Assets = new Dictionary<string,string> {
            ["Andy"] = "assets/bg/remake-andy.png",
            ["TheGirl"] = "assets/bg/remake-thegirl.png",
            ["Blue"] = "assets/bg/remake-blue.png",
            ["ShopGirl"] = "assets/bg/remake-shopgirl.png",
            ["Boy"] = "assets/bg/remake-boy.png",
            ["Pig"] = "assets/bg/remake-pig.png",
            ["King"] = "assets/bg/remake-king.png",
            ["过场1"] = "assets/bg/fanmade-01.png",
            ["过场2"] = "assets/bg/fanmade-02.png",
            ["武器"] = "assets/bg/official-weapons.jpg",
            ["7代主角1"] = "assets/bg/official-hero1.jpg",
            ["7代主角2"] = "assets/bg/official-hero2.jpg",
            ["黑铁众"] = "assets/bg/official-ironcrew.jpg",
            ["诺亚方舟1"] = "assets/bg/official-ark.jpg",
        };
    }
}
