#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <chrono>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>
#include "ShaderSources.h"

// Build-only tool. The absolute compiler path is hash-checked by the native
// toolchain gate; loading it explicitly avoids the machine's DLL search order.
int wmain(int argc, wchar_t** argv) {
    if (argc!=3 || !std::filesystem::path(argv[1]).is_absolute()) {
        std::fwprintf(stderr,L"Usage: ShaderBake <pinned-compiler-dll> <generated-header>\n");
        return 2;
    }
    HMODULE compiler=LoadLibraryExW(argv[1],nullptr,
        LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_SYSTEM32);
    if (!compiler) { std::fprintf(stderr,"Cannot load pinned HLSL compiler: %lu\n",GetLastError());return 1; }
    auto compile=reinterpret_cast<decltype(&D3DCompile)>(GetProcAddress(compiler,"D3DCompile"));
    if (!compile) { FreeLibrary(compiler);return 1; }
    const struct { const char* source;const char* entry;const char* profile; } shaders[] = {
        {Shader,"VS","vs_4_0"},{Shader,"PS","ps_4_0"},
        {WeatherShader,"WVS","vs_4_0"},{WeatherShader,"WPS","ps_4_0"},
        {BulletShader,"BVS","vs_4_0"},{BulletShader,"BPS","ps_4_0"},
        {CombatFxShader,"FVS","vs_4_0"},{CombatFxShader,"FPS","ps_4_0"},
        {RayShader,"RVS","vs_4_0"},{RayShader,"RPS","ps_4_0"},
        {PointLightShader,"LVS","vs_4_0"},{PointLightShader,"LPS","ps_4_0"},
        {HudRasterShader,"HVS","vs_4_0"},{HudRasterShader,"HPS","ps_4_0"}
    };
    std::ofstream output(std::filesystem::path(argv[2]),std::ios::binary|std::ios::trunc);
    if (!output) { FreeLibrary(compiler);return 1; }
    output<<"// Generated by ShaderBake. Build output only; edit ShaderSources.h / Ray*Shader.h.\n"
        "#pragma once\n#include <cstddef>\nnamespace CompositorShaders {\n"
        "struct Bytecode { const unsigned char* data; std::size_t size; };\n";
    int result=0;
    for (const auto& shader:shaders) {
        Microsoft::WRL::ComPtr<ID3DBlob> code,errors;
        std::string source=std::string(PointLightShared)+shader.source;
        auto start=std::chrono::steady_clock::now();
        HRESULT hr=compile(source.data(),source.size(),"compositor-probe",nullptr,nullptr,
            shader.entry,shader.profile,D3DCOMPILE_OPTIMIZATION_LEVEL3|D3DCOMPILE_WARNINGS_ARE_ERRORS,
            0,code.GetAddressOf(),errors.GetAddressOf());
        if (FAILED(hr)) {
            std::fprintf(stderr,"HLSL %s failed: 0x%08lx\n",shader.entry,static_cast<unsigned long>(hr));
            if (errors) std::fwrite(errors->GetBufferPointer(),1,errors->GetBufferSize(),stderr);
            result=1;break;
        }
        auto data=static_cast<const unsigned char*>(code->GetBufferPointer());
        output<<"inline constexpr unsigned char "<<shader.entry<<"Bytes[] = {\n";
        for (std::size_t i=0;i<code->GetBufferSize();++i) {
            if (i%24==0) output<<"    ";
            output<<static_cast<unsigned int>(data[i])<<',';
            if (i%24==23) output<<'\n';
        }
        output<<"\n};\ninline constexpr Bytecode "<<shader.entry<<"{"<<shader.entry
            <<"Bytes,sizeof("<<shader.entry<<"Bytes)};\n";
        std::printf("[ShaderBake] %s bytes=%zu elapsedMs=%.1f\n",shader.entry,code->GetBufferSize(),
            std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count());
    }
    output<<"}\n";output.close();
    if (!output) result=1;
    FreeLibrary(compiler);
    return result;
}
