'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),cp=require('child_process');
const {chromium}=require('../../launcher/perf/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),config=path.join(root,'data/map/map_definition.json');
async function main(){
 const browser=await chromium.launch({executablePath:path.join(process.env['ProgramFiles(x86)'],'Microsoft/Edge/Application/msedge.exe'),headless:true});
 const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[],before=fs.readFileSync(config);
 let appliedId='';
 page.on('pageerror',e=>errors.push(e.message));
 const button=name=>page.getByRole('button',{name,exact:true});
 const ready=async()=>{await page.waitForSelector('#mw-x');await page.frameLocator('iframe').locator('.map-authoring-target.is-selected').waitFor();};
 const frame=()=>page.frames().find(f=>f.url().includes('/map/authoring/preview.html'));
 const view=()=>frame().evaluate(()=>MapPanel.authoring.getView());
 const verified=()=>page.waitForFunction(()=>document.querySelector('.mw-status').textContent.includes('候选已校验'));
 const reset=async()=>{await button('放弃草稿并重读').click();await page.waitForFunction(()=>document.querySelector('.mw-status').textContent.includes('编辑预览即时'));};
 try{
  await page.goto('http://127.0.0.1:18765/');await ready();
  assert.equal(Math.round((await page.locator('.map-workbench-panel').boundingBox()).width),1280);
  const frameBox=await page.locator('iframe').boundingBox();assert(frameBox.width>900&&frameBox.height>500,'canvas-first viewport too small');
  assert.equal(await page.frameLocator('iframe').locator('.map-page-tab').count(),4);
  const originalView=await view(),selected=page.frameLocator('iframe').locator('.map-authoring-target.is-selected'),box=await selected.boundingBox();
  const oldX=Number(await page.locator('#mw-x').inputValue()),outerScale=frameBox.width/await page.locator('iframe').evaluate(n=>n.clientWidth);
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+15,box.y+box.height/2+6);await page.mouse.up();
  await verified();assert(Math.abs(Number(await page.locator('#mw-x').inputValue())-oldX-15/(originalView.scale*outerScale))<.05,'drag projection drift');
  await reset();
  const canvasBefore=await frame().evaluate(()=>document.getElementById('map-stage-canvas').width);
  await button('+').click();await page.waitForFunction(()=>document.querySelector('.mw-zoom').textContent==='125%');
  assert.equal(await frame().evaluate(()=>document.getElementById('map-stage-canvas').width),canvasBefore,'zoom allocated a larger backing canvas');
  const wheelStage=await page.frameLocator('iframe').locator('#map-stage-frame').boundingBox(),wheelBefore=await view();
  await page.mouse.move(wheelStage.x+wheelStage.width*.6,wheelStage.y+wheelStage.height*.45);await page.mouse.wheel(0,-120);
  await page.waitForFunction(()=>document.querySelector('.mw-zoom').textContent!=='125%');
  assert((await view()).camera.zoom>wheelBefore.camera.zoom,'wheel did not zoom');
  const stage=await page.frameLocator('iframe').locator('#map-stage-frame').boundingBox(),panBefore=await view();
  await page.mouse.move(stage.x+stage.width*.5,stage.y+stage.height*.6);await page.mouse.down({button:'middle'});await page.mouse.move(stage.x+stage.width*.5+25,stage.y+stage.height*.6+10);await page.mouse.up({button:'middle'});
  assert(Math.abs((await view()).camera.x-panBefore.camera.x)>10,'pan did not move camera');
  await button('聚焦所选').click();assert((await view()).camera.zoom>=.5);
  await button('玩家取景').click();await page.waitForFunction(()=>document.querySelector('.mw-zoom').textContent==='100%');assert.equal((await view()).camera.zoom,1);
  await button('专注画布').click();await page.waitForFunction(()=>document.querySelector('.workbench-shell').dataset.profile==='canvas-editor-focus');
  assert((await page.locator('iframe').boundingBox()).width>1200);
  await page.screenshot({path:path.join(root,'tmp/map-workbench/workbench-focus.png')});
  await page.frameLocator('iframe').locator('#map-stage-frame').focus();await page.keyboard.press('Escape');
  await page.waitForFunction(()=>document.querySelector('.workbench-shell').dataset.profile==='canvas-editor');
  await page.getByRole('checkbox',{name:'编辑边框'}).uncheck();await page.frameLocator('iframe').locator('.map-authoring-targets').waitFor({state:'hidden'});
  await page.getByRole('checkbox',{name:'编辑边框'}).check();
  const firstFilter=JSON.parse(before).pages.base.filters.find(x=>x.id!=='all'&&x.id!=='hierarchy').id;
  await page.frameLocator('iframe').locator('.map-filter-hotspot[data-filter-id="'+firstFilter+'"]').click();
  assert.equal((await view()).filterId,firstFilter,'production filter did not change');
  await page.frameLocator('iframe').locator('.map-filter-hotspot[data-filter-id="all"]').click();
  assert(fs.readFileSync(config).equals(before),'inspection camera changed project');
  await page.getByLabel('对象类别',{exact:true}).selectOption('filter');
  await page.waitForSelector('#mw-order');assert.equal(await page.locator('#mw-x').count(),0,'legacy filter XY is presented as live layout');
  await page.getByLabel('对象类别',{exact:true}).selectOption('scene');await ready();
  await page.screenshot({path:path.join(root,'tmp/map-workbench/workbench-revised.png')});
  const x=Number(await page.locator('#mw-x').inputValue());await page.locator('#mw-x').fill(String(x+8));await page.locator('#mw-y').focus();await verified();
  assert(fs.readFileSync(config).equals(before),'preview changed file');
  await page.getByRole('checkbox',{name:'对比保存前'}).check();assert.equal(Number(await page.locator('#mw-x').inputValue()),x);
  await page.getByRole('checkbox',{name:'对比保存前'}).uncheck();assert.equal(Number(await page.locator('#mw-x').inputValue()),x+8);
  const downloadPromise=page.waitForEvent('download');await button('导出草稿').click();const draft=fs.readFileSync(await (await downloadPromise).path());assert.equal(JSON.parse(draft).version,1);
  await reset();await page.locator('input[type=file]').setInputFiles({name:'map-draft.json',mimeType:'application/json',buffer:draft});
  await page.waitForFunction(()=>document.querySelector('.mw-status').textContent.includes('草稿已导入'));
  assert.equal(Number(await page.locator('#mw-x').inputValue()),x+8);
  const duplicate=JSON.parse(draft);duplicate.changes.push(duplicate.changes[0]);
  await page.locator('input[type=file]').setInputFiles({name:'duplicate-draft.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(duplicate))});
  await page.waitForFunction(()=>document.querySelector('.mw-status').textContent.includes('同一地图对象只能'));
  await button('重新读取 / 核对结果').click();await verified();assert.equal(Number(await page.locator('#mw-x').inputValue()),x+8,'refresh lost draft');
  await button('保存到项目').click();await page.waitForFunction(()=>document.querySelector('.mw-status').textContent.includes('已保存到项目'));
  appliedId=await page.getByLabel('已保存的修改',{exact:true}).inputValue();assert(!fs.readFileSync(config).equals(before),'apply did not save');
  await page.reload();await ready();assert.equal(Number(await page.locator('#mw-x').inputValue()),x+8,'restart did not load saved geometry');
  assert.equal(await frame().evaluate(()=>MapPanelData.getPage('base').sceneVisuals[0].rect.x),x+8,'production preview did not use saved geometry');
  await page.getByLabel('已保存的修改',{exact:true}).selectOption(appliedId);
  await button('撤回所选修改').click();await page.waitForFunction(()=>document.querySelector('.mw-status').textContent.includes('恢复原配置'));
  assert(fs.readFileSync(config).equals(before),'undo did not restore user bytes');
  const operation=appliedId;
  await button('关闭').click();
  await page.evaluate(({operation,draft})=>localStorage.setItem('cf7.map.workbench.draft.v1',JSON.stringify({digest:draft.expectedDigest,changes:draft.changes,operation,operationKind:'apply',unknown:true})),{operation,draft:JSON.parse(draft)});
  await button('打开地图工作台').click();await page.waitForFunction(()=>document.querySelector('.mw-status').textContent.includes('当前文件为修改前内容'));
  assert(await button('保存到项目').isEnabled());assert((await page.locator('.mw-count').textContent()).includes('1 个对象'),'reconciliation lost draft');
  await button('重新读取 / 核对结果').click();await verified();assert.equal(Number(await page.locator('#mw-x').inputValue()),x+8);await reset();
  await page.frameLocator('iframe').locator('.map-page-tab[data-page-id="school"]').click();
  await page.waitForFunction(()=>document.querySelector('[aria-label="地图页面"]').value==='school');
  await page.getByLabel('对象类别',{exact:true}).selectOption('avatar');await page.getByLabel('室友预览').selectOption('female');
  await page.frameLocator('iframe').locator('img[src*="roommate-female"]').first().waitFor();
  assert(await page.frameLocator('iframe').locator('.map-avatar.is-visible').count()>0);
  await button('关闭').click();await page.waitForFunction(()=>document.getElementById('panel-container').hidden);
  await button('打开地图工作台').click();await ready();
  assert(fs.readFileSync(config).equals(before));assert.deepEqual(errors,[]);
  console.log('PASS production MapPanel iframe, canvas-first layout, DPI drag, bounded zoom/pan, focus, tabs, avatars, drafts, save/restart, exact undo and reopen');
 }finally{
  await browser.close();
  if(appliedId&&!fs.readFileSync(config).equals(before)){
   const result=cp.spawnSync(path.join(process.env.LOCALAPPDATA,'Microsoft/dotnet/dotnet.exe'),[path.join(__dirname,'bin/Release/net10.0/MapWorkbench.dll'),'api',root],{input:JSON.stringify({op:'undo',operationId:appliedId}),encoding:'utf8'});
   if(!JSON.parse(result.stdout).success)throw new Error('测试修改未撤回，拒绝覆盖后来修改。');
  }
 }
}
main().catch(e=>{console.error(e);process.exitCode=1;});
