# encoding: utf-8
"""
Scan all XFL directories and FLA files under flashswf/ for linkage exports.
Produces:
  1. data/items/asset_source_map.xml  — linkageId → source SWF mapping
  2. Console report with conflict detection

Usage:
  python tools/linkage_scanner/scan_linkage.py [--exclude-unused] [--xml-only]
"""
import struct, zlib, re, os, sys, glob, xml.sax.saxutils

sys.stdout.reconfigure(encoding='utf-8')

TOOL_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(os.path.dirname(TOOL_DIR))
BASE = os.path.join(PROJECT_ROOT, 'flashswf')
OUTPUT_XML = os.path.join(PROJECT_ROOT, 'data', 'items', 'asset_source_map.xml')
LINKAGE_RE = re.compile(r'linkageExportForAS="true".*?linkageIdentifier="([^"]+)"')

results = {}       # linkageId -> set(swf_rel_paths)  (deduplicated per source)
source_counts = {}  # swf_rel -> count
EXCLUDE_UNUSED = '--exclude-unused' in sys.argv
XML_ONLY = '--xml-only' in sys.argv


def rel_swf(path):
    """Convert source path to relative .swf path from project root."""
    r = os.path.relpath(path, PROJECT_ROOT).replace(os.sep, '/')
    return r


def should_skip(swf_rel):
    """Skip unused/ sources when --exclude-unused is set."""
    return EXCLUDE_UNUSED and '/unused/' in swf_rel


def scan_xfl(xfl_dir):
    lib_dir = os.path.join(xfl_dir, 'LIBRARY')
    if not os.path.isdir(lib_dir):
        return
    swf_rel = rel_swf(xfl_dir) + '.swf'
    if should_skip(swf_rel):
        return
    count = 0
    for xml_file in glob.glob(os.path.join(lib_dir, '**', '*.xml'), recursive=True):
        with open(xml_file, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read(2000)
        m = LINKAGE_RE.search(content)
        if m:
            lid = m.group(1)
            results.setdefault(lid, set()).add(swf_rel)
            count += 1
    if count > 0:
        source_counts[swf_rel] = count


def scan_fla(fla_path):
    swf_rel = rel_swf(fla_path)
    swf_rel = swf_rel[:-4] + '.swf'  # .fla -> .swf
    if should_skip(swf_rel):
        return

    # Skip if XFL directory exists (already scanned)
    xfl_dir = fla_path[:-4]
    if os.path.exists(os.path.join(xfl_dir, 'DOMDocument.xml')):
        return

    with open(fla_path, 'rb') as f:
        data = f.read()

    count = 0
    offset = 0
    while offset < len(data) - 4:
        if data[offset:offset + 4] != b'PK\x03\x04':
            break
        comp_method = struct.unpack_from('<H', data, offset + 8)[0]
        comp_size = struct.unpack_from('<I', data, offset + 18)[0]
        fname_len = struct.unpack_from('<H', data, offset + 26)[0]
        extra_len = struct.unpack_from('<H', data, offset + 28)[0]
        fname_raw = data[offset + 30:offset + 30 + fname_len]
        file_data_start = offset + 30 + fname_len + extra_len
        file_data = data[file_data_start:file_data_start + comp_size]

        try:
            fname = fname_raw.decode('utf-8')
        except UnicodeDecodeError:
            offset = file_data_start + comp_size
            continue

        if fname.startswith('LIBRARY/') and fname.endswith('.xml'):
            if comp_method == 8:  # deflate
                try:
                    content = zlib.decompress(file_data, -15).decode('utf-8')
                except Exception:
                    content = ''
            else:
                content = file_data.decode('utf-8', errors='replace')

            m = LINKAGE_RE.search(content)
            if m:
                lid = m.group(1)
                results.setdefault(lid, set()).add(swf_rel)
                count += 1

        offset = file_data_start + comp_size

    if count > 0:
        source_counts[swf_rel] = count


def write_xml():
    """Write asset_source_map.xml with all linkage → source mappings."""
    os.makedirs(os.path.dirname(OUTPUT_XML), exist_ok=True)
    esc = xml.sax.saxutils.escape

    lines = ['<?xml version="1.0" encoding="UTF-8"?>']
    lines.append('<assetSourceMap>')
    lines.append('  <!-- Auto-generated by tools/linkage_scanner/scan_linkage.py -->')
    lines.append('  <!-- DO NOT EDIT MANUALLY -->')

    # Separate conflicts for easy visual identification
    conflicts = {}
    clean = {}
    for lid in sorted(results.keys()):
        sources = sorted(results[lid])
        if len(sources) > 1:
            conflicts[lid] = sources
        else:
            clean[lid] = sources[0]

    # Write clean entries
    lines.append('')
    lines.append(f'  <!-- {len(clean)} unique assets -->')
    for lid, src in sorted(clean.items()):
        lines.append(f'  <asset id="{esc(lid)}" swf="{esc(src)}" />')

    # Write conflicts in a separate section
    if conflicts:
        lines.append('')
        lines.append(f'  <!-- {len(conflicts)} CONFLICTS: same ID in multiple sources -->')
        for lid, sources in sorted(conflicts.items()):
            lines.append(f'  <conflict id="{esc(lid)}">')
            for s in sources:
                lines.append(f'    <source swf="{esc(s)}" />')
            lines.append('  </conflict>')

    lines.append('</assetSourceMap>')
    lines.append('')

    with open(OUTPUT_XML, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f'Written: {os.path.relpath(OUTPUT_XML, PROJECT_ROOT)}')


def main():
    # 1. Scan all XFL directories
    for dom in glob.glob(os.path.join(BASE, '**', 'DOMDocument.xml'), recursive=True):
        scan_xfl(os.path.dirname(dom))

    # 2. Scan all FLA files (skip those with existing XFL)
    for fla in glob.glob(os.path.join(BASE, '**', '*.fla'), recursive=True):
        scan_fla(fla)

    # Write XML output
    write_xml()

    if XML_ONLY:
        return

    # Console report
    total_unique = len(results)
    conflicts = {k: v for k, v in results.items() if len(v) > 1}

    print(f'\n=== Total: {total_unique} unique linkageIdentifiers from {len(source_counts)} sources ===')
    if EXCLUDE_UNUSED:
        print('  (unused/ sources excluded)')
    print()

    print(f'=== CONFLICTS (same ID in multiple SWFs): {len(conflicts)} ===')
    for lid, sources in sorted(conflicts.items()):
        print(f'  {lid}:')
        for s in sorted(sources):
            print(f'    - {s}')

    print()
    print('=== Exports per source ===')
    for src, cnt in sorted(source_counts.items(), key=lambda x: -x[1]):
        print(f'  {cnt:4d}  {src}')


if __name__ == '__main__':
    main()
