import org.flashNight.gesh.regexp.RegExp; // Ensure you have a custom RegExp class or use AS2's native RegExp if available
import org.flashNight.gesh.object.*;
import org.flashNight.gesh.fntl.*;
import org.flashNight.gesh.string.StringUtils;

/**
 * FNTLParser class designed to parse FNTL (FlashNight Text Language) inputs.
 * 
 * Features:
 * - Parses key-value pairs, nested tables, and arrays.
 * - Handles inline tables.
 * - Supports various data types including strings, numbers, booleans, and date-times.
 * - Provides robust error handling and reporting.
 */
class org.flashNight.gesh.fntl.FNTLParser {
    private var tokens:Array;            // List of tokens generated by the lexer
    private var position:Number;         // Current token position
    private var current:Object;          // Current context object being populated
    private var root:Object;             // Root object representing the parsed FNTL data
    private var hasErrorFlag:Boolean;    // Flag indicating if an error has occurred
    private var text:String;             // Original FNTL text for error reporting

    // Precompiled and cached RegExp instances for performance
    private static var numberRegExp:RegExp = new RegExp("^-?\\d+(\\.\\d+)?([eE][+-]?\\d+)?$", "");
    private static var dateTimeRegExp:RegExp = new RegExp("^\\d{4}-\\d{2}-\\d{2}[Tt ][0-2]\\d:[0-5]\\d:[0-5]\\d(\\.\\d+)?([Zz]|([+-][0-2]\\d:[0-5]\\d))?$", "");
    private static var booleanRegExp:RegExp = new RegExp("^(true|false)$", "i");
    private static var specialFloatRegExp:RegExp = new RegExp("^(nan|inf|-inf)$", "i");

    /**
     * Constructor to initialize the FNTLParser.
     * @param tokens List of tokens generated by the FNTLLexer.
     * @param text Original FNTL text for error reporting.
     */
    public function FNTLParser(tokens:Array, text:String) {
        this.tokens = tokens;
        this.position = 0;
        this.root = new Object();
        this.current = this.root;
        this.hasErrorFlag = false;
        this.text = text;  // Preserve original text for error localization
    }

    /**
     * Parses the list of tokens and constructs the FNTL object.
     * @return The parsed FNTL object.
     */
    public function parse():Object {
        while (this.position < this.tokens.length) {
            var token:Object = this.tokens[this.position];

            switch (token.type) {
                case "KEY":
                    this.handleKey(token);
                    break;
                case "TABLE_HEADER":
                    this.handleTableHeader(token.value);
                    this.position++;
                    break;
                case "TABLE_ARRAY":
                    this.handleTableArray(token.value);
                    this.position++;
                    break;
                case "INLINE_TABLE":
                    this.handleInlineTable(token.value);
                    this.position++;
                    break;
                default:
                    this.error("未处理的 token 类型: " + token.type, "");
                    this.position++;
                    break;
            }

            if (this.hasErrorFlag) {
                break; // Stop parsing on critical errors
            }
        }
        return this.root;
    }

    /**
     * Checks if the parser has encountered any errors.
     * @return True if errors exist, else false.
     */
    public function hasError():Boolean {
        return this.hasErrorFlag;
    }

    /**
     * Handles a key-value pair token.
     * @param token The KEY token to process.
     */
    private function handleKey(token:Object):Void {
        var key:String = token.value;
        var nextPos:Number = this.position + 1;

        if (nextPos >= this.tokens.length || this.tokens[nextPos].type != "EQUALS") {
            this.error("期望 EQUALS 标记", key);
            return;
        }

        var valuePos:Number = nextPos + 1;
        if (valuePos >= this.tokens.length) {
            this.error("值缺失", key);
            return;
        }

        var valueToken:Object = this.tokens[valuePos];
        var value:Object = this.parseValue(valueToken);

        this.current[key] = value;
        this.position = valuePos + 1;
    }

    /**
     * Parses a value token and returns its corresponding AS2 object.
     * @param token The value token to parse.
     * @return The parsed value.
     */
    private function parseValue(token:Object):Object {
        switch (token.type) {
            case "STRING":
                return token.value;
            case "INTEGER":
                return Number(token.value);
            case "FLOAT":
                return this.parseSpecialFloat(token.value);
            case "BOOLEAN":
                return token.value == true;
            case "DATETIME":
                return this.parseDateTime(token.value);
            case "ARRAY":
                return this.parseArray(token.value);
            case "INLINE_TABLE":
                return this.parseInlineTable(token.value);
            case "NULL":
                return null;
            default:
                this.error("未知的值类型: " + token.type, "");
                return null;
        }
    }

    /**
     * Parses special floating-point values (NaN, Infinity, -Infinity).
     * @param value The string representation.
     * @return The corresponding AS2 number.
     */
    private function parseSpecialFloat(value:String):Object {
        switch (value.toLowerCase()) {
            case "nan":
                return Number.NaN;
            case "inf":
                return Number.POSITIVE_INFINITY;
            case "-inf":
                return Number.NEGATIVE_INFINITY;
            default:
                return Number(value);
        }
    }

    /**
     * Parses a date-time string and returns it in ISO8601 format.
     * @param dateTimeStr The date-time string to parse.
     * @return The formatted ISO8601 date-time string or null if parsing fails.
     */
    private function parseDateTime(dateTimeStr:String):String {
        if (!FNTLParser.dateTimeRegExp.test(dateTimeStr)) {
            this.error("无效的日期时间格式: " + dateTimeStr, "");
            return null;
        }

        var hasZ:Boolean = dateTimeStr.charAt(dateTimeStr.length - 1).toLowerCase() == "z";
        if (hasZ) {
            dateTimeStr = dateTimeStr.substring(0, dateTimeStr.length - 1);
        }

        var separatorPos:Number = dateTimeStr.indexOf("T");
        if (separatorPos == -1) {
            separatorPos = dateTimeStr.indexOf(" ");
        }

        var datePart:String;
        var timePart:String;

        if (separatorPos == -1) {
            // Assume only date part
            datePart = dateTimeStr;
            timePart = "00:00:00"; // Default time is midnight
        } else {
            datePart = dateTimeStr.substring(0, separatorPos);
            timePart = dateTimeStr.substring(separatorPos + 1);
        }

        // Parse date part
        var dateComponents:Array = datePart.split("-");
        if (dateComponents.length != 3) {
            this.error("无效的日期格式: " + datePart, "");
            return null;
        }
        var year:Number = Number(dateComponents[0]);
        var month:Number = Number(dateComponents[1]) - 1; // AS2 months are 0-based
        var day:Number = Number(dateComponents[2]);

        // Parse time part
        var timeComponents:Array = timePart.split(":");
        if (timeComponents.length < 2) {
            this.error("无效的时间格式: " + timePart, "");
            return null;
        }
        var hours:Number = Number(timeComponents[0]);
        var minutes:Number = Number(timeComponents[1]);
        var seconds:Number = 0;
        if (timeComponents.length >= 3) {
            var secPart:String = timeComponents[2];
            var secComponents:Array = secPart.split(".");
            seconds = Number(secComponents[0]);
            // Handle fractional seconds if needed
        }

        var dateObj:Date;
        if (hasZ) {
            // Create UTC time
            var utcTime:Number = Date.UTC(year, month, day, hours, minutes, seconds);
            dateObj = new Date(utcTime);
        } else {
            // Create local time
            dateObj = new Date(year, month, day, hours, minutes, seconds);
        }

        // Format to ISO8601 string
        var isoStr:String = this.formatDateToISO8601(dateObj, hasZ);
        return isoStr;
    }

    /**
     * Formats a Date object to an ISO8601 string.
     * @param dateObj The Date object to format.
     * @param isUTC Whether to format as UTC.
     * @return The ISO8601 formatted string.
     */
    private function formatDateToISO8601(dateObj:Date, isUTC:Boolean):String {
        var year:String = String(isUTC ? dateObj.getUTCFullYear() : dateObj.getFullYear());
        var month:String = this.padZero(isUTC ? dateObj.getUTCMonth() + 1 : dateObj.getMonth() + 1);
        var day:String = this.padZero(isUTC ? dateObj.getUTCDate() : dateObj.getDate());
        var hours:String = this.padZero(isUTC ? dateObj.getUTCHours() : dateObj.getHours());
        var minutes:String = this.padZero(isUTC ? dateObj.getUTCMinutes() : dateObj.getMinutes());
        var seconds:String = this.padZero(isUTC ? dateObj.getUTCSeconds() : dateObj.getSeconds());
        var timezoneSuffix:String = isUTC ? "Z" : "";
        return year + "-" + month + "-" + day + "T" + hours + ":" + minutes + ":" + seconds + timezoneSuffix;
    }

    /**
     * Pads a number with a leading zero if necessary.
     * @param value The number to pad.
     * @return The padded string.
     */
    private function padZero(value:Number):String {
        return value < 10 ? "0" + value : String(value);
    }

    /**
     * Handles a table header token by updating the current context.
     * Supports nested table paths.
     * @param tableName The name of the table.
     */
    private function handleTableHeader(tableName:String):Void {
        var path:Array = tableName.split(".");
        var current:Object = this.root;
        for (var i:Number = 0; i < path.length; i++) {
            var part:String = path[i];
            if (current[part] == undefined || current[part] == null) {
                current[part] = new Object();
            } else if (!(current[part] instanceof Object)) {
                this.error("键名冲突，无法将非表格类型转换为表格：" + part, "");
                return;
            }
            current = current[part];
        }
        this.current = current;
    }

    /**
     * Handles a table array token by adding a new table to the array.
     * @param arrayName The name of the table array.
     */
    private function handleTableArray(arrayName:String):Void {
        var path:Array = arrayName.split(".");
        var current:Object = this.root;
        for (var i:Number = 0; i < path.length; i++) {
            var part:String = path[i];
            if (i == path.length - 1) {
                if (!(current[part] instanceof Array)) {
                    current[part] = new Array();
                }
                var newTable:Object = new Object();
                current[part].push(newTable);
                current = newTable;
            } else {
                if (current[part] == undefined || current[part] == null) {
                    current[part] = new Object();
                } else if (current[part] instanceof Array) {
                    current = current[part][current[part].length - 1];
                } else {
                    current = current[part];
                }
            }
        }
        this.current = current;
    }

    /**
     * Parses an array token into an AS2 array.
     * Ensures all elements are of the same type.
     * @param arrayData The array token value.
     * @return The parsed array or null if there's an error.
     */
    private function parseArray(arrayData:Array):Array {
        var array:Array = new Array();
        var elementType:String = null;

        for (var i:Number = 0; i < arrayData.length; i++) {
            var token:Object = arrayData[i];
            var value:Object = this.parseValue(token);

            if (elementType == null && value != null) {
                elementType = typeof(value);
            } else if (value != null && typeof(value) != elementType) {
                this.error("数组元素类型不一致，预期: " + elementType + "，实际: " + typeof(value), "");
                return null;
            }

            array.push(value);
        }

        return array;
    }

    /**
     * Parses an inline table string into an object.
     * @param tableStr The inline table string.
     * @return The parsed inline table object.
     */
    private function parseInlineTable(tableStr:String):Object {
        var table:Object = new Object();

        if (tableStr.charAt(0) == "{" && tableStr.charAt(tableStr.length - 1) == "}") {
            tableStr = tableStr.substring(1, tableStr.length - 1);
        }

        var pairs:Array = this.splitInlineTablePairs(tableStr);
        for (var i:Number = 0; i < pairs.length; i++) {
            var pairStr:String = StringUtils.trim(pairs[i]);
            if (pairStr.length == 0) continue;

            var eqIndex:Number = pairStr.indexOf("=");
            if (eqIndex == -1) {
                this.error("内联表格中的键值对缺少 '=': " + pairs[i], "");
                continue;
            }
            var key:String = StringUtils.trim(pairStr.substring(0, eqIndex));
            var valueStr:String = StringUtils.trim(pairStr.substring(eqIndex + 1));

            if (key.length == 0) {
                this.error("内联表格中的键为空: " + pairs[i], "");
                continue;
            }

            var value:Object = this.parseInlineTableValue(valueStr);
            table[key] = value;
        }
        return table;
    }

    /**
     * Splits inline table key-value pairs by commas, considering nested structures.
     * Prevents splitting within nested arrays or tables.
     * @param tableStr The inline table string.
     * @return An array of key-value pair strings.
     */
    private function splitInlineTablePairs(tableStr:String):Array {
        var pairs:Array = new Array();
        var currentPair:String = "";
        var nestingLevel:Number = 0;

        for (var i:Number = 0; i < tableStr.length; i++) {
            var c:String = tableStr.charAt(i);
            if (c == "," && nestingLevel == 0) {
                pairs.push(currentPair);
                currentPair = "";
            } else {
                if (c == "{" || c == "[") {
                    nestingLevel++;
                } else if (c == "}" || c == "]") {
                    nestingLevel--;
                }
                currentPair += c;
            }
        }

        if (currentPair.length > 0) {
            pairs.push(currentPair);
        }

        return pairs;
    }

    /**
     * Parses a value string from an inline table.
     * @param valueStr The value string to parse.
     * @return The parsed value.
     */
    private function parseInlineTableValue(valueStr:String):Object {
        if (valueStr.charAt(0) == "\"" || valueStr.charAt(0) == "'") {
            return this.stripQuotes(valueStr);
        } else if (FNTLParser.booleanRegExp.test(valueStr)) {
            return valueStr.toLowerCase() == "true";
        } else if (FNTLParser.specialFloatRegExp.test(valueStr)) {
            return this.parseSpecialFloat(valueStr);
        } else if (FNTLParser.numberRegExp.test(valueStr)) {
            return Number(valueStr);
        } else if (FNTLParser.dateTimeRegExp.test(valueStr)) {
            return this.parseDateTime(valueStr);
        } else if (valueStr.charAt(0) == "[") {
            // Assuming that nested arrays within inline tables are handled similarly
            var nestedLexer:FNTLLexer = new FNTLLexer(valueStr);
            var nestedTokens:Array = new Array();
            var tok:Object;
            while ((tok = nestedLexer.getNextToken()) != null) {
                nestedTokens.push(tok);
            }
            var nestedParser:FNTLParser = new FNTLParser(nestedTokens, valueStr);
            return nestedParser.parseArray(nestedTokens);
        } else if (valueStr.charAt(0) == "{") {
            return this.parseInlineTable(valueStr);
        }
        return valueStr;
    }

    /**
     * Strips surrounding quotes from a string.
     * @param str The string with quotes.
     * @return The string without surrounding quotes.
     */
    private function stripQuotes(str:String):String {
        if ((str.charAt(0) == "\"" && str.charAt(str.length - 1) == "\"") ||
            (str.charAt(0) == "'" && str.charAt(str.length - 1) == "'")) {
            return str.substring(1, str.length - 1);
        }
        return str;
    }

    /**
     * Handles an inline table token by parsing and merging it into the current context.
     * @param inlineTableStr The inline table string.
     */
    private function handleInlineTable(inlineTableStr:String):Void {
        var inlineTable:Object = this.parseInlineTable(inlineTableStr);
        for (var key:String in inlineTable) {
            if (this.current[key] != undefined) {
                this.error("键重复: " + key, "");
            } else {
                this.current[key] = inlineTable[key];
            }
        }
    }

    /**
     * Handles parsing errors by setting the error flag and logging the error with localization.
     * @param message The error message.
     * @param key The key associated with the error, if any.
     */
    private function error(message:String, key:String):Void {
        var lineInfo:String = "行: " + this.getLineNumber() + ", 列: " + this.getColumnNumber();
        trace("错误: " + message + (key.length > 0 ? " - 键: " + key : "") + " 在 " + lineInfo);
        this.hasErrorFlag = true;
    }

    /**
     * Retrieves the current line number based on the position in the text.
     * @return The current line number.
     */
    private function getLineNumber():Number {
        var lines:Array = this.text.substring(0, this.position).split("\n");
        return lines.length;
    }

    /**
     * Retrieves the current column number based on the position in the text.
     * @return The current column number.
     */
    private function getColumnNumber():Number {
        var lines:Array = this.text.substring(0, this.position).split("\n");
        var lastLine:String = lines[lines.length - 1];
        return lastLine.length + 1;
    }
}
