_root.闪客之夜 = 1192433993;//119的注视
_root.暂停 = false;
_root.磨擦阻力 = 0.2;
_root.最大下落速度 = 25;
_root.重力加速度 = 1;
_root.重力加速度基准 = 1;
_root.钝感硬直时间 = 70;
_root.集中攻击目标 = "无";
_root.命令 = "跟随";
_root.控制目标全自动 = false;
_root.全鼠标控制 = false;
_root.控制目标 = "玩家0";
_root._quality = "MEDIUM";
_root.血腥开关 = true;
_root.基础身价值 = 1000;
_root.打怪掉钱机率 = 6;
_root.佣兵个数限制 = 5;
_root.吃药冷却时间 = 3000;
_root.是否阴影 = true;
_root.是否视觉元素 = true;
_root.是否打击数字特效 = true;
_root.当前通关的关卡 = "";
_root.难度等级 = 1;
_root.关卡地图帧值 = "房间";
_root.佣兵是否出战信息 = [0, 0, 0, 0, 0];

// _root.打怪掉K点机率 = 8;//逼用没有
// _root.佣兵数据刷新机率 = 999;
// _root.人类hp_min = 200;
// _root.人类hp_max = 1000;
// _root.防御上限_min = 95000;
// _root.防御上限_max = 99000;
// _root.战场关闭聊天 = false;
// _root.音效音量 = 100;
// _root.是否默认播放音乐 = true;
