#!/usr/bin/env sh
/usr/local/bin/mtasc -cp "src" -swf ActionStep.swf -header 800:600:20 -pack org/actionstep -pack org/actionstep/images -pack org/actionstep/constants -pack org/actionstep/images org/actionstep/test/ASTestMain -main
puts 'Build complete.'
