'use strict';

const fs = require('fs');
const path = require('path');
const { diagnostic, sortDiagnostics } = require('./catalog');
const {
    buildRuntimeProjection,
    cssFamily,
    cssVariable,
    roleStack,
} = require('./projection');
const { buildCompatibilityManifest } = require('./manifest');

const HEADER = 'Generated by tools/fontctl. Edit fonts/fonts.xml, then run `node tools/fontctl/cli.js generate`.';

function fontFormat(format) {
    if (format === 'ttf') return 'truetype';
    if (format === 'otf') return 'opentype';
    return format;
}

function generateCss(projection) {
    const lines = [`/* ${HEADER} */`, ''];
    for (const asset of projection.assets.filter((item) => item.targets.includes('web'))) {
        for (const faceId of asset.faces) {
            const face = projection.faces[faceId];
            lines.push('@font-face {');
            lines.push(`    font-family: ${cssFamily(face.alias)};`);
            lines.push(`    src: url('${projection.virtualFontOrigin}${encodeURIComponent(asset.file)}') format('${fontFormat(asset.format)}');`);
            lines.push(`    font-weight: ${face.weight};`);
            lines.push(`    font-style: ${face.style};`);
            lines.push(`    font-stretch: ${face.stretch};`);
            lines.push('    font-display: swap;');
            lines.push('}');
            lines.push('');
        }
    }

    lines.push(':root {');
    for (const roleId of Object.keys(projection.roles).filter((id) => id.startsWith('web.'))) {
        lines.push(`    ${cssVariable(roleId)}: ${roleStack(projection, roleId)};`);
    }
    const compatibilityVariables = {
        '--intel-font-body': 'web.intelligence.body',
        '--intel-font-title': 'web.intelligence.title',
        '--intel-font-note': 'web.intelligence.note',
        '--intel-font-outburst': 'web.intelligence.outburst',
        '--intel-font-emotional': 'web.intelligence.emotional',
        '--intel-font-archive': 'web.intelligence.archive',
        '--intel-font-character-neat': 'web.intelligence.character-neat',
        '--intel-font-character-rough': 'web.intelligence.character-rough',
        '--intel-font-character-plain': 'web.intelligence.character-plain',
        '--intel-font-character-weary': 'web.intelligence.character-weary',
        '--intel-font-mono': 'web.intelligence.terminal',
    };
    for (const [name, roleId] of Object.entries(compatibilityVariables)) {
        lines.push(`    ${name}: var(${cssVariable(roleId)});`);
    }
    lines.push('}');
    lines.push('');

    for (const [presetId, preset] of Object.entries(projection.presets)) {
        const roleIds = Object.keys(preset.binds).filter((id) => id.startsWith('web.'));
        if (!roleIds.length) continue;
        lines.push(`[data-cf7-font-presets~="${presetId}"] {`);
        for (const roleId of roleIds) {
            lines.push(`    ${cssVariable(roleId)}: ${roleStack(projection, roleId, [presetId])};`);
        }
        lines.push('}');
        lines.push('');
    }
    return `${lines.join('\n').trimEnd()}\n`;
}

function generateJs(projection) {
    const data = JSON.stringify(projection);
    return `/* ${HEADER} */
(function (root, factory) {
    var api = factory(${data});
    if (typeof module === 'object' && module.exports) module.exports = api;
    else root.CF7FontCatalog = api;
}(typeof globalThis !== 'undefined' ? globalThis : this, function (catalog) {
    'use strict';

    function quoteFamily(value) {
        return '"' + String(value).replace(/\\\\/g, '\\\\\\\\').replace(/"/g, '\\\\"') + '"';
    }
    function variable(roleId) {
        return '--cf7-font-' + String(roleId).replace(/\\./g, '-');
    }
    function normalizedPresets(value) {
        if (!value) return [];
        if (Array.isArray(value)) return value.filter(function (item) { return typeof item === 'string'; });
        return [String(value)];
    }
    function faceOrder(roleId, presets) {
        var role = catalog.roles[roleId];
        if (!role) return [];
        var override = null;
        normalizedPresets(presets).forEach(function (presetId) {
            var preset = catalog.presets[presetId];
            if (preset && preset.binds[roleId]) override = preset.binds[roleId];
        });
        var result = override ? [override] : [];
        role.faces.forEach(function (faceId) { if (result.indexOf(faceId) < 0) result.push(faceId); });
        return result;
    }
    function role(roleId, presets) {
        var item = catalog.roles[roleId];
        if (!item) return null;
        return faceOrder(roleId, presets).map(function (faceId) { return quoteFamily(catalog.faces[faceId].alias); })
            .concat(item.system.map(function (entry) { return quoteFamily(entry.family); }))
            .concat(item.generic.map(function (entry) { return entry.family; }))
            .join(', ');
    }
    function canvasFont(roleId, sizePx, options) {
        options = options || {};
        var stack = role(roleId, options.presets);
        if (!stack) return null;
        return (options.style || 'normal') + ' ' + (options.weight || 400) + ' ' + Number(sizePx) + 'px ' + stack;
    }
    function applyRoleContext(element, options) {
        if (!element || !element.style) return false;
        var presets = normalizedPresets(options && options.presets);
        var previous = element.__cf7FontProperties || [];
        previous.forEach(function (name) { element.style.removeProperty(name); });
        var touched = [];
        Object.keys(catalog.roles).forEach(function (roleId) {
            if (roleId.indexOf('web.') !== 0) return;
            var name = variable(roleId);
            element.style.setProperty(name, role(roleId, presets));
            touched.push(name);
        });
        element.__cf7FontProperties = touched;
        if (presets.length) element.setAttribute('data-cf7-font-presets', presets.join(' '));
        else element.removeAttribute('data-cf7-font-presets');
        return true;
    }
    function legacyFamily(rawFamily) {
        var key = String(rawFamily || '').trim().toLocaleLowerCase('en-US');
        var roleId = catalog.legacyFamilies[key];
        return roleId ? role(roleId) : null;
    }
    function loadRole(roleId, options) {
        options = options || {};
        if (typeof document === 'undefined' || !document.fonts || typeof document.fonts.load !== 'function') return Promise.resolve([]);
        var size = Number(options.size || 16);
        var style = options.style || 'normal';
        var weight = options.weight || 400;
        var loads = faceOrder(roleId, options.presets).map(function (faceId) {
            return document.fonts.load(style + ' ' + weight + ' ' + size + 'px ' + quoteFamily(catalog.faces[faceId].alias), options.text || '');
        });
        return Promise.allSettled(loads);
    }
    function prewarm(roleIds, options) {
        return Promise.allSettled((roleIds || []).map(function (roleId) { return loadRole(roleId, options); }));
    }
    return Object.freeze({
        catalog: catalog,
        role: role,
        cssVariable: variable,
        canvasFont: canvasFont,
        applyRoleContext: applyRoleContext,
        legacyFamily: legacyFamily,
        loadRole: loadRole,
        prewarm: prewarm
    });
}));
`;
}

function desiredFiles(catalog, maps, outputRoot, compatibilityManifestPath) {
    const projection = buildRuntimeProjection(catalog, maps);
    const files = [
        { path: path.join(outputRoot, 'font-catalog.json'), content: `${JSON.stringify(projection, null, 2)}\n` },
        { path: path.join(outputRoot, 'font-catalog.css'), content: generateCss(projection) },
        { path: path.join(outputRoot, 'font-catalog.js'), content: generateJs(projection) },
    ];
    if (compatibilityManifestPath) {
        files.push({
            path: compatibilityManifestPath,
            content: `${JSON.stringify(buildCompatibilityManifest(projection), null, 2)}\n`,
        });
    }
    return {
        projection,
        files,
    };
}

function generateCatalog(catalog, maps, outputRoot, checkOnly, compatibilityManifestPath) {
    const diagnostics = [];
    const desired = desiredFiles(catalog, maps, outputRoot, compatibilityManifestPath);
    for (const item of desired.files) {
        const relative = path.basename(item.path);
        let actual = null;
        try {
            actual = fs.readFileSync(item.path, 'utf8');
        } catch (error) {
            if (error.code !== 'ENOENT') throw error;
        }
        if (actual === item.content) continue;
        if (checkOnly) {
            diagnostics.push(diagnostic('GENERATED_DRIFT', `生成物缺失或过期：${relative}`, item.path));
            continue;
        }
        fs.mkdirSync(path.dirname(item.path), { recursive: true });
        const temporary = `${item.path}.${process.pid}.${Date.now()}.tmp`;
        fs.writeFileSync(temporary, item.content, 'utf8');
        fs.renameSync(temporary, item.path);
    }
    return {
        diagnostics: sortDiagnostics(diagnostics),
        projection: desired.projection,
        files: desired.files.map((item) => item.path),
    };
}

module.exports = { desiredFiles, generateCatalog, generateCss, generateJs };
