from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import fontTools
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont


CHARACTERS = "0123456789/%MP-"
FONT_SPECS = (
    ("lcd-std", "245_LCD Std.ttf"),
    ("aero", "2_Aero.ttf"),
)


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest().upper()


def csharp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_font(font_id: str, source_path: Path) -> dict[str, object]:
    source_bytes = source_path.read_bytes()
    font = TTFont(
        source_path,
        lazy=False,
        recalcBBoxes=False,
        recalcTimestamp=False,
    )
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    hmtx = font["hmtx"].metrics
    head = font["head"]
    hhea = font["hhea"]
    os2 = font["OS/2"]
    glyf = font["glyf"]

    glyphs: list[dict[str, object]] = []
    for character in CHARACTERS:
        codepoint = ord(character)
        glyph_name = cmap.get(codepoint)
        if glyph_name is None:
            raise RuntimeError(
                f"{source_path.name} is missing U+{codepoint:04X}.")
        glyph = glyf[glyph_name]
        glyph.recalcBounds(glyf)
        pen = SVGPathPen(glyph_set)
        glyph_set[glyph_name].draw(pen)
        path = pen.getCommands()
        advance, left_side_bearing = hmtx[glyph_name]
        glyphs.append(
            {
                "character": character,
                "codepoint": f"U+{codepoint:04X}",
                "glyphName": glyph_name,
                "advance": advance,
                "leftSideBearing": left_side_bearing,
                "bounds": [
                    glyph.xMin,
                    glyph.yMin,
                    glyph.xMax,
                    glyph.yMax,
                ],
                "path": path,
                "pathSha256": sha256_bytes(path.encode("utf-8")),
            }
        )

    return {
        "id": font_id,
        "sourceFile": source_path.name,
        "sourceByteLength": len(source_bytes),
        "sourceSha256": sha256_bytes(source_bytes),
        "unitsPerEm": head.unitsPerEm,
        "headBounds": [head.xMin, head.yMin, head.xMax, head.yMax],
        "hhea": {
            "ascent": hhea.ascent,
            "descent": hhea.descent,
            "lineGap": hhea.lineGap,
        },
        "os2": {
            "typoAscender": os2.sTypoAscender,
            "typoDescender": os2.sTypoDescender,
            "typoLineGap": os2.sTypoLineGap,
            "winAscent": os2.usWinAscent,
            "winDescent": os2.usWinDescent,
            "fsType": os2.fsType,
        },
        "glyphs": glyphs,
    }


def render_csharp(fonts: list[dict[str, object]]) -> bytes:
    lines = [
        "// <auto-generated />",
        "#nullable enable",
        "",
        "namespace CF7Launcher.Guardian.Hud.PlayerInfo;",
        "",
        "internal static partial class PlayerInfoPathGlyphAtlasData",
        "{",
        f'    internal const string GeneratorVersion = "{fontTools.__version__}";',
        f'    internal const string Characters = "{CHARACTERS}";',
        "",
        "    internal static readonly PlayerInfoPathFontData[] Fonts =",
        "    [",
    ]
    for font_index, font in enumerate(fonts):
        lines.extend(
            [
                "        new(",
                f'            {csharp_string(str(font["id"]))},',
                f'            {csharp_string(str(font["sourceFile"]))},',
                f'            {csharp_string(str(font["sourceSha256"]))},',
                f'            {font["sourceByteLength"]},',
                f'            {font["unitsPerEm"]},',
                f'            {font["hhea"]["ascent"]},',
                f'            {font["hhea"]["descent"]},',
                f'            {font["os2"]["fsType"]},',
                "            [",
            ]
        )
        glyphs = font["glyphs"]
        for glyph_index, glyph in enumerate(glyphs):
            suffix = "," if glyph_index + 1 < len(glyphs) else ""
            character_literal = (
                "'\\''" if glyph["character"] == "'" else
                f"'{glyph['character']}'"
            )
            lines.append(
                "                new("
                f"{character_literal}, "
                f"{glyph['advance']}, "
                f"{glyph['leftSideBearing']}, "
                f"{csharp_string(str(glyph['path']))}){suffix}"
            )
        lines.extend(
            [
                "            ])" +
                ("," if font_index + 1 < len(fonts) else ""),
            ]
        )
    lines.extend(["    ];", "}", ""])
    return "\n".join(lines).encode("utf-8")


def build_provenance(
    fonts: list[dict[str, object]],
    source_swf_path: Path,
    source_swf_bytes: bytes,
    generated_path: Path,
    generated_bytes: bytes,
) -> bytes:
    payload = {
        "schema": "cf7.player-info-hud.glyph-atlas-provenance.v1",
        "status": "derived_path_atlas_generated",
        "generator": {
            "path": "tools/player-info-hud/generate-player-info-glyph-atlas.py",
            "fontToolsVersion": fontTools.__version__,
            "characters": CHARACTERS,
            "coordinateContract": (
                "font units, y-up; render with "
                "translate(originX,baselineY) scale(fontPx/unitsPerEm,"
                "-fontPx/unitsPerEm)"
            ),
            "advanceContract": (
                "advance font-space cursor by glyph.advance; apply alignment "
                "to the sum of advances before the font-unit transform"
            ),
        },
        "sourceBinding": {
            "xfl": "flashswf/UI/玩家信息界面/玩家信息界面.xfl",
            "xflFontItems": [
                {
                    "fontId": "lcd-std",
                    "name": "嵌入字体/LCD Std",
                    "itemId": "664e350a-000085f3",
                },
                {
                    "fontId": "aero",
                    "name": "嵌入字体/Aero",
                    "itemId": "664e3cd0-00000bd4",
                },
            ],
            "flashCandidateChildPath": source_swf_path.as_posix(),
            "flashCandidateChildByteLength": len(source_swf_bytes),
            "flashCandidateChildSha256": sha256_bytes(source_swf_bytes),
            "extraction": (
                "FFDec font export from the source-bound PlayerInfo child SWF; "
                "the exported TTF files remain under ignored tmp/ and are not distributed"
            ),
        },
        "fonts": [
            {
                "id": font["id"],
                "sourceFile": font["sourceFile"],
                "sourceByteLength": font["sourceByteLength"],
                "sourceSha256": font["sourceSha256"],
                "unitsPerEm": font["unitsPerEm"],
                "fsType": font["os2"]["fsType"],
                "glyphCount": len(font["glyphs"]),
                "glyphPathClosureSha256": sha256_bytes(
                    b"\0".join(
                        (
                            str(glyph["character"]).encode("utf-8") +
                            b"\0" +
                            str(glyph["path"]).encode("utf-8")
                        )
                        for glyph in font["glyphs"]
                    )
                ),
            }
            for font in fonts
        ],
        "distributionBoundary": {
            "runtimeIncludes": "derived outline paths and metrics only",
            "runtimeExcludes": "TTF/OTF/font program bytes",
            "os2FsTypeObserved": 0,
            "licenseConclusion": (
                "fsType=0 permits installable embedding at the font-table level, "
                "but is not an independent legal-license conclusion; reuse remains "
                "bound to the repository's existing Flash HUD source asset"
            ),
        },
        "output": {
            "path": generated_path.as_posix(),
            "byteLength": len(generated_bytes),
            "sha256": sha256_bytes(generated_bytes),
            "encoding": "UTF-8 without BOM, LF",
        },
    }
    return (
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
    ).encode("utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the deterministic PlayerInfo path-glyph C# data from "
            "explicit FFDec-exported font files. Font binaries are never copied."
        )
    )
    parser.add_argument("--font-root", required=True, type=Path)
    parser.add_argument("--source-swf", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--provenance", required=True, type=Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.source_swf.is_absolute():
        raise RuntimeError("--source-swf must be repository-relative.")
    source_swf_bytes = args.source_swf.read_bytes()
    fonts = [
        load_font(font_id, args.font_root / file_name)
        for font_id, file_name in FONT_SPECS
    ]
    generated_bytes = render_csharp(fonts)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(generated_bytes)

    provenance_bytes = build_provenance(
        fonts,
        args.source_swf,
        source_swf_bytes,
        args.output,
        generated_bytes,
    )
    args.provenance.parent.mkdir(parents=True, exist_ok=True)
    args.provenance.write_bytes(provenance_bytes)

    print(
        f"{args.output}: {len(generated_bytes)} B "
        f"SHA-256 {sha256_bytes(generated_bytes)}"
    )
    print(
        f"{args.provenance}: {len(provenance_bytes)} B "
        f"SHA-256 {sha256_bytes(provenance_bytes)}"
    )


if __name__ == "__main__":
    main()
