// Generated by tools/build-book-definition.py from data/stages/books/repair-campus.json.
class org.flashNight.arki.scene.BookDefinition {
    private static var _data:Object;
    private static var _loading:Boolean = false;
    private static var _loaded:Boolean = false;
    public static function get():Object {
        if (_data == null) _data = fallback();
        return _data;
    }
    public static function ready():Boolean { return _loaded; }
    public static function load():Void {
        if (_loading || _loaded) return;
        _loading = true;
        var loader:org.flashNight.gesh.json.LoadJson.BaseJSONLoader = new org.flashNight.gesh.json.LoadJson.BaseJSONLoader(
            "data/stages/books/repair-campus.runtime.json", "LiteJSON");
        loader.load(function(data:Object):Void {
            org.flashNight.arki.scene.BookDefinition.accept(data);
        }, function(error:String):Void {
            org.flashNight.arki.scene.BookDefinition.loadFailed();
        });
    }
    public static function loadFailed():Void { _loading = false; }
    public static function accept(data:Object):Boolean {
        _loading = false;
        if (!valid(data)) return false;
        _data = data; _loaded = true; return true;
    }
    // Runtime defense for damaged/manual files; the generator also verifies all item/unit identities.
    public static function valid(data:Object):Boolean {
        if (!shape(data, fallback(), 0) || data.schema !== "playable-book.v1"
                || data.id !== "repair-campus" || data.stageName !== "书中历险-修理大学"
                || data.maps.length < 6 || data.maps.length > 8) return false;
        for (var i:Number = 0; i < data.maps.length; i++) {
            var map:Object = data.maps[i];
            if (map.background.indexOf("/") >= 0 || map.background.indexOf("\\") >= 0
                    || map.background.indexOf("..") >= 0 || map.background.substr(-4) !== ".swf"
                    || map.enemies.length == 0 || map.equipment.length == 0 || map.armor.length == 0
                    || map.level.length != 2 || map.level[0] < 1 || map.level[1] > 60 || map.level[0] > map.level[1]
                    || map.count.length != 2 || map.count[0] < 1 || map.count[1] > 8 || map.count[0] > map.count[1]
                    || map.waves < 1 || map.waves > 8) return false;
        }
        return data.bossEncounter.mapIndex == data.maps.length - 1 && data.regularSp <= 100
            && data.firstClearSp <= 100 && data.recordSpPerTier <= 100 && data.recordSp <= 100
            && data.kBudget.mapCount == 6 && data.kBudget.guaranteed <= 1000 && data.kBudget.randomMax <= 1000
            && data.optionalLoot.percent <= 100 && data.optionalLoot.firstMap <= data.optionalLoot.lastMap
            && data.optionalLoot.lastMap < data.maps.length;
    }
    private static function shape(value, example, depth:Number):Boolean {
        if (depth > 12 || value == null || typeof value != typeof example) return false;
        if (typeof example == "number") return !isNaN(value) && isFinite(value) && value >= 0 && value <= 1000000000 && (Math.floor(example) != example || Math.floor(value) == value);
        if (typeof example == "string") return value.length <= 4096;
        if (typeof example == "boolean") return true;
        if (example instanceof Array) {
            if (!(value instanceof Array) || value.length > 256 || (example.length > 0 && value.length == 0)) return false;
            for (var i:Number = 0; i < value.length; i++) {
                if (example.length == 0 || !shape(value[i], example[Math.min(i, example.length - 1)], depth + 1)) return false;
            }
            return true;
        }
        for (var key:String in example) {
            if (key == "dialogue") {
                if (!(value[key] instanceof Array) || value[key].length > 32) return false;
                for (var lineIndex:Number = 0; lineIndex < value[key].length; lineIndex++) {
                    var line:Object = value[key][lineIndex];
                    if (typeof line.speaker != "string" || line.speaker.length > 40
                            || typeof line.text != "string" || line.text.length == 0 || line.text.length > 160) return false;
                }
            } else if (!shape(value[key], example[key], depth + 1)) return false;
        }
        for (var extra:String in value) if (example[extra] == undefined) return false;
        return true;
    }

    private static function fallback():Object {
        return {
    schema: "playable-book.v1",
    id: "repair-campus",
    title: "修理大学",
    stageName: "书中历险-修理大学",
    unlockTask: 21,
    regularSp: 5,
    firstClearSp: 0,
    recordSpPerTier: 0,
    recordMinutes: [
        30,
        25,
        20
    ],
    startingMoney: 8000,
    startingSkillPoints: 120,
    loot: {
        equipmentChance: 80,
        supplyChance: 25,
        experienceItem: "经验值",
        moneyItem: "金币",
        healingCount: 3,
        support: [
            {
                name: "普通mp药剂",
                count: 4,
                kind: "mana"
            },
            {
                name: "书中弹药补给包",
                count: 1,
                kind: "ammo"
            },
            {
                name: "普通手雷",
                count: 4,
                kind: "grenade"
            }
        ],
        medicalItem: "战场复合急救包",
        armorWaves: 2,
        skillPointItem: "技能点"
    },
    maps: [
        {
            title: "上学路上",
            background: "gk12_1_BG.swf",
            enemies: [
                44,
                45
            ],
            level: [
                1,
                3
            ],
            waves: 3,
            count: [
                2,
                4
            ],
            experience: 9000,
            money: [
                1500,
                2200
            ],
            equipment: [
                "水管",
                "棒球棒",
                "PPK",
                "单管霰弹枪"
            ],
            armor: [
                "黑框眼镜",
                "军绿防弹衣",
                "新手裤子",
                "黑色皮手套",
                "道钉手套"
            ],
            healingItem: "普通hp药剂",
            manaItem: "普通mp药剂",
            skillPoints: 40,
            materials: [
                {
                    name: "军用帆布",
                    count: 3
                },
                {
                    name: "弹簧",
                    count: 2
                },
                {
                    name: "手柄皮",
                    count: 1
                }
            ],
            dialogue: [
                {
                    speaker: "Andy",
                    text: "先练两下。别钱还没挣到，自己先倒了……"
                }
            ]
        },
        {
            title: "校门口的混混",
            background: "gk13_1_BG.swf",
            enemies: [
                48,
                49
            ],
            level: [
                3,
                5
            ],
            waves: 3,
            count: [
                2,
                4
            ],
            experience: 45000,
            money: [
                2200,
                3200
            ],
            equipment: [
                "破旧的军刀",
                "UZI",
                "AK47",
                "M1915Chauchat",
                "单管霰弹枪",
                "DBHshotgun"
            ],
            armor: [
                "废城军装帽",
                "废城军装上装",
                "废城军装下装",
                "废城军装手套",
                "废城军装鞋",
                "道钉手套"
            ],
            healingItem: "普通hp药剂",
            manaItem: "普通mp药剂",
            skillPoints: 50,
            materials: [
                {
                    name: "可塑式钢板",
                    count: 3
                },
                {
                    name: "绳扣穿孔片",
                    count: 2
                },
                {
                    name: "强化石",
                    count: 12
                }
            ],
            dialogue: [
                {
                    speaker: "对方",
                    text: "人来了，往那边走！"
                },
                {
                    speaker: "Andy",
                    text: "别跑！水管是不是你们砸的？"
                }
            ]
        },
        {
            title: "拦路的一伙",
            background: "gk13_2_BG.swf",
            enemies: [
                447,
                448
            ],
            level: [
                7,
                9
            ],
            waves: 3,
            count: [
                2,
                3
            ],
            experience: 77000,
            money: [
                3200,
                4500
            ],
            equipment: [
                "铁钉球棒",
                "破旧的军刀",
                "M16A1",
                "雷明登870",
                "HKG3",
                "M1915Chauchat"
            ],
            armor: [
                "战术猪鼻式防毒面具",
                "A兵团制式战术背心",
                "A兵团制式战术裤",
                "A兵团制式战术手套",
                "A兵团制式战术皮鞋",
                "小型拳套"
            ],
            healingItem: "加强抗生素药剂",
            manaItem: "加强mp药剂",
            skillPoints: 60,
            materials: [
                {
                    name: "高耐力橡胶",
                    count: 2
                },
                {
                    name: "螺丝套件",
                    count: 2
                },
                {
                    name: "战术背带",
                    count: 1
                }
            ],
            dialogue: [
                {
                    speaker: "学员",
                    text: "这人怎么还往前走？"
                },
                {
                    speaker: "另一人",
                    text: "先别管，表现要记分的。"
                },
                {
                    speaker: "Andy",
                    text: "打人还算成绩？你们这什么学校啊？"
                }
            ]
        },
        {
            title: "没完没了",
            background: "gk12_3_BG.swf",
            enemies: [
                436,
                437
            ],
            level: [
                9,
                11
            ],
            waves: 3,
            count: [
                2,
                3
            ],
            experience: 140000,
            money: [
                3600,
                5000
            ],
            equipment: [
                "单刀",
                "消防斧",
                "M16A1",
                "雷明登870",
                "HKSL8",
                "M4A1",
                "M249",
                "M79式榴弹发射器"
            ],
            armor: [
                "沙漠军装头盔",
                "沙漠军装背心",
                "沙漠军装裤",
                "沙漠军装手套",
                "沙漠军装皮鞋",
                "大型拳套"
            ],
            healingItem: "加强抗生素药剂",
            manaItem: "加强mp药剂",
            skillPoints: 70,
            materials: [
                {
                    name: "二阶复合防御组件",
                    count: 3
                },
                {
                    name: "防沙皮革",
                    count: 3
                },
                {
                    name: "强化石",
                    count: 18
                }
            ],
            dialogue: []
        },
        {
            title: "还有下一组",
            background: "gk12_2_BG.swf",
            enemies: [
                449,
                450
            ],
            level: [
                5,
                7
            ],
            waves: 3,
            count: [
                2,
                3
            ],
            experience: 110000,
            money: [
                4000,
                5500
            ],
            equipment: [
                "单刀",
                "战术双刀",
                "HKG3",
                "M4A1",
                "雷明登870",
                "HKSL8",
                "M249",
                "M79式榴弹发射器"
            ],
            armor: [
                "黑铁死士围巾",
                "废城防弹军装上装",
                "废城加强军装下装",
                "黑铁死士手套",
                "黑铁死士鞋",
                "大型拳套"
            ],
            healingItem: "大HP药剂",
            manaItem: "大MP药剂",
            skillPoints: 70,
            materials: [
                {
                    name: "二阶复合防御组件",
                    count: 2
                },
                {
                    name: "高耐力橡胶",
                    count: 2
                },
                {
                    name: "强化石",
                    count: 24
                }
            ],
            dialogue: [
                {
                    speaker: "学员",
                    text: "不是说他知道规则吗？"
                },
                {
                    speaker: "另一人",
                    text: "先顾好自己！"
                },
                {
                    speaker: "Andy",
                    text: "什么规则？谁跟我说过了？"
                }
            ]
        },
        {
            title: "谁在记分",
            background: "gk12_4_BG.swf",
            enemies: [
                444,
                446
            ],
            level: [
                11,
                13
            ],
            waves: 3,
            count: [
                2,
                3
            ],
            experience: 120000,
            money: [
                4500,
                6000
            ],
            equipment: [
                "战术双刀",
                "消防斧",
                "M4A1",
                "雷明登870警用型",
                "HKSL8",
                "M249",
                "M79式榴弹发射器"
            ],
            armor: [
                "战术耳机加遮阳帽",
                "战术套装上衣",
                "战术套装裤子",
                "黑铁游侠手套",
                "黑铁游侠战靴",
                "大型拳套"
            ],
            healingItem: "大HP药剂",
            manaItem: "大MP药剂",
            skillPoints: 70,
            materials: [
                {
                    name: "防沙皮革",
                    count: 2
                },
                {
                    name: "绳扣穿孔片",
                    count: 1
                },
                {
                    name: "强化石",
                    count: 24
                }
            ],
            dialogue: [
                {
                    speaker: "学员",
                    text: "老师在校门口。有话你找他说。"
                },
                {
                    speaker: "Andy",
                    text: "老师？那我倒要问问，他是怎么教的！"
                }
            ]
        },
        {
            title: "最后一堂体育课",
            background: "gk12_5_BG.swf",
            enemies: [
                455
            ],
            level: [
                14,
                14
            ],
            waves: 1,
            count: [
                1,
                1
            ],
            experience: 160000,
            money: [
                6000,
                8000
            ],
            equipment: [
                "战术双刀",
                "雷明登870警用型"
            ],
            armor: [
                "战术耳机加遮阳帽",
                "战术套装上衣",
                "战术套装裤子",
                "黑铁游侠手套",
                "黑铁游侠战靴",
                "大型拳套"
            ],
            healingItem: "大HP药剂",
            manaItem: "大MP药剂",
            skillPoints: 0,
            materials: [],
            dialogue: []
        }
    ],
    equipment: [
        "水管",
        "棒球棒",
        "破旧的军刀",
        "铁钉球棒",
        "单刀",
        "消防斧",
        "战术双刀",
        "白色中山上装",
        "白色中山装裤子",
        "黑色板鞋",
        "鲁格MK3",
        "PPK",
        "UZI",
        "单管霰弹枪",
        "DBHshotgun",
        "雷明登870",
        "雷明登870警用型",
        "AK47",
        "M1915Chauchat",
        "M16A1",
        "HKG3",
        "M4A1",
        "HKSL8",
        "黑框眼镜",
        "军绿防弹衣",
        "新手裤子",
        "黑色皮手套",
        "废城军装帽",
        "废城军装上装",
        "废城军装下装",
        "废城军装手套",
        "废城军装鞋",
        "战术猪鼻式防毒面具",
        "A兵团制式战术背心",
        "A兵团制式战术裤",
        "A兵团制式战术手套",
        "A兵团制式战术皮鞋",
        "沙漠军装头盔",
        "沙漠军装背心",
        "沙漠军装裤",
        "沙漠军装手套",
        "沙漠军装皮鞋",
        "黑铁死士围巾",
        "废城防弹军装上装",
        "废城加强军装下装",
        "黑铁死士手套",
        "黑铁死士鞋",
        "战术耳机加遮阳帽",
        "战术套装上衣",
        "战术套装裤子",
        "黑铁游侠手套",
        "黑铁游侠战靴",
        "M249",
        "M79式榴弹发射器",
        "道钉手套",
        "小型拳套",
        "大型拳套"
    ],
    supplies: [
        "战场医疗包",
        "战场突击强化包",
        "战场防护强化包",
        "战场全量弹药包"
    ],
    skills: [
        "小跳",
        "兴奋剂",
        "铁布衫",
        "寸拳",
        "气动波",
        "移动射击",
        "刀剑攻击",
        "枪械攻击",
        "拳脚攻击",
        "口才",
        "独行者"
    ],
    skillMaxUnlockLevel: 15,
    buildChoices: [
        {
            afterMap: 1,
            voucher: "书中初阶配给凭证",
            levelCeiling: 9,
            poolId: "repair-campus.initial",
            choiceItem: "书中初阶自选配给包",
            options: [
                {
                    grade: "low",
                    name: "书中冲锋配给包",
                    title: "初阶·冲锋穿透",
                    description: "7级UZI两把、磁稳贯穿弹两份、冲锋枪弹药24份。双持配给，两把各装一份插件；贯穿射击会降低射速。",
                    weapon: "UZI",
                    weaponCount: 2,
                    mods: [
                        "磁稳贯穿弹"
                    ],
                    consumables: [
                        {
                            name: "冲锋枪通用弹药",
                            count: 24
                        }
                    ]
                },
                {
                    grade: "low",
                    name: "书中步榴配给包",
                    title: "初阶·步榴协同",
                    description: "7级AK47、磁稳贯穿弹、M203榴弹发射器、步枪弹药8份、榴弹6份。贯穿射击配合下挂爆发。",
                    weapon: "AK47",
                    mods: [
                        "磁稳贯穿弹",
                        "M203榴弹发射器"
                    ],
                    consumables: [
                        {
                            name: "突击步枪通用弹药",
                            count: 8
                        },
                        {
                            name: "榴弹弹药",
                            count: 6
                        }
                    ]
                },
                {
                    grade: "low",
                    name: "书中霰弹配给包",
                    title: "初阶·集中霰弹",
                    description: "8级雷明登870、霰弹枪口收束器、磁稳贯穿弹、霰弹18份。集中霰弹并获得贯穿；与镇暴弹属于互斥的弹药改装。",
                    weapon: "雷明登870",
                    mods: [
                        "霰弹枪口收束器",
                        "磁稳贯穿弹"
                    ],
                    consumables: [
                        {
                            name: "12号霰弹弹药",
                            count: 18
                        }
                    ]
                },
                {
                    grade: "low",
                    name: "书中军刀配给包",
                    title: "初阶·军刀突进",
                    description: "9级破旧的军刀、绳扣穿孔片、手柄皮、石英磨刀石、中蓝6瓶、手雷4枚。磨刀石提升威力并锁定物理伤害。",
                    weapon: "破旧的军刀",
                    mods: [
                        "绳扣穿孔片",
                        "手柄皮",
                        "石英磨刀石"
                    ],
                    consumables: [
                        {
                            name: "加强mp药剂",
                            count: 6
                        },
                        {
                            name: "普通手雷",
                            count: 4
                        }
                    ]
                }
            ]
        },
        {
            afterMap: 3,
            voucher: "书中进阶配给凭证",
            levelCeiling: 13,
            poolId: "repair-campus.advanced",
            choiceItem: "书中进阶自选配给包",
            options: [
                {
                    grade: "medium",
                    name: "书中机枪配给包",
                    title: "进阶·机枪压制",
                    description: "13级M249、水冷机构、磁稳贯穿弹、机枪弹药4份。贯穿火力支持持续压制；插件会增加负重、降低射速，可自行决定是否安装。",
                    weapon: "M249",
                    mods: [
                        "水冷机构",
                        "磁稳贯穿弹"
                    ],
                    consumables: [
                        {
                            name: "机枪通用弹药",
                            count: 4
                        }
                    ]
                },
                {
                    grade: "medium",
                    name: "书中榴弹配给包",
                    title: "进阶·榴弹爆破",
                    description: "12级M79式榴弹发射器两把、榴弹24份、普通手雷6枚。双持爆炸火力适合应对集群，仍需规划换弹和后续弹药。",
                    weapon: "M79式榴弹发射器",
                    weaponCount: 2,
                    mods: [],
                    consumables: [
                        {
                            name: "榴弹弹药",
                            count: 24
                        },
                        {
                            name: "普通手雷",
                            count: 6
                        }
                    ]
                },
                {
                    grade: "medium",
                    name: "书中镇暴配给包",
                    title: "进阶·霰弹控场",
                    description: "8级雷明登870、霰弹枪口收束器、八门金锁镇暴弹、霰弹18份、手雷6枚。镇暴弹偏向对群控制，与磁稳贯穿弹不能同时安装。",
                    weapon: "雷明登870",
                    mods: [
                        "霰弹枪口收束器",
                        "八门金锁镇暴弹"
                    ],
                    consumables: [
                        {
                            name: "12号霰弹弹药",
                            count: 18
                        },
                        {
                            name: "普通手雷",
                            count: 6
                        }
                    ]
                },
                {
                    grade: "medium",
                    name: "书中双刀配给包",
                    title: "进阶·双刀突进",
                    description: "13级战术双刀、绳扣穿孔片、石英磨刀石、大蓝6瓶、手雷6枚。两枚插件适配双刀的两个插槽，强化瞬步斩与物理威力。",
                    weapon: "战术双刀",
                    mods: [
                        "绳扣穿孔片",
                        "石英磨刀石"
                    ],
                    consumables: [
                        {
                            name: "大MP药剂",
                            count: 6
                        },
                        {
                            name: "普通手雷",
                            count: 6
                        }
                    ]
                }
            ]
        }
    ],
    ammoBundle: {
        name: "书中弹药补给包",
        contents: [
            {
                name: "手枪通用弹药",
                count: 8
            },
            {
                name: "冲锋枪通用弹药",
                count: 10
            },
            {
                name: "突击步枪通用弹药",
                count: 6
            },
            {
                name: "12号霰弹弹药",
                count: 12
            },
            {
                name: "机枪通用弹药",
                count: 2
            },
            {
                name: "狙击步枪通用弹药",
                count: 4
            },
            {
                name: "榴弹弹药",
                count: 3
            }
        ]
    },
    bossEncounter: {
        mapIndex: 6,
        instanceName: "bookCampusTeacher",
        intervalFrames: 150,
        maxAlive: 2,
        maxRanged: 1,
        groups: [
            {
                hpRatio: 0.75,
                level: 8,
                pools: [
                    [
                        44
                    ],
                    [
                        45
                    ],
                    [
                        48
                    ],
                    [
                        49
                    ]
                ]
            },
            {
                hpRatio: 0.5,
                level: 11,
                pools: [
                    [
                        447,
                        448
                    ],
                    [
                        436,
                        437
                    ]
                ]
            },
            {
                hpRatio: 0.25,
                level: 13,
                pools: [
                    [
                        449,
                        450
                    ],
                    [
                        444,
                        446
                    ]
                ]
            }
        ],
        rangedTypes: [
            44,
            449,
            450
        ],
        supplies: [
            {
                name: "战场复合急救包",
                count: 1
            },
            {
                name: "大MP药剂",
                count: 2
            },
            {
                name: "书中弹药补给包",
                count: 1
            },
            {
                name: "普通手雷",
                count: 3
            }
        ]
    },
    minorChoices: [
        {
            afterMap: 0,
            poolId: "repair-campus.opening",
            choiceItem: "书中入学特训自选包",
            levelCeiling: 15,
            options: []
        },
        {
            afterMap: 2,
            poolId: "repair-campus.synergy",
            choiceItem: "书中流派协同自选包",
            levelCeiling: 15,
            options: []
        },
        {
            afterMap: 4,
            poolId: "repair-campus.mastery",
            choiceItem: "书中战技精进自选包",
            levelCeiling: 15,
            options: []
        },
        {
            afterMap: 5,
            poolId: "repair-campus.final",
            choiceItem: "书中决战补给自选包",
            levelCeiling: 15,
            options: []
        }
    ],
    kBudget: {
        mapCount: 6,
        guaranteed: 200,
        randomMax: 100
    },
    optionalLoot: {
        firstMap: 2,
        lastMap: 5,
        percent: 75
    },
    recordSp: 45
};
    }
}
