@echo off
chcp 65001 >nul
setlocal EnableDelayedExpansion

echo ========================================
echo  Flash CS6 自动化编译环境配置
echo ========================================
echo.

:: ---- 1. 定位项目根目录 ----
set "SCRIPT_DIR=%~dp0"
:: 去掉末尾反斜杠
set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"
:: 项目根 = scripts 的上一级
for %%I in ("%SCRIPT_DIR%") do set "PROJECT_DIR=%%~dpI"
set "PROJECT_DIR=%PROJECT_DIR:~0,-1%"
echo [INFO] 项目目录: %PROJECT_DIR%

:: ---- 2. 配置 mm.cfg ----
set "MM_CFG=%USERPROFILE%\mm.cfg"
(
echo ErrorReportingEnable=1
echo TraceOutputFileEnable=1
echo MaxWarnings=0
) > "%MM_CFG%"
echo [OK] mm.cfg: %MM_CFG%

:: ---- 3. 定位 Flash CS6 语言目录 ----
set "FLASH_CFG_BASE=%LOCALAPPDATA%\Adobe\Flash CS6"
set "LANG_DIR="
for /d %%D in ("%FLASH_CFG_BASE%\*") do (
    if exist "%%D\Configuration\Commands" (
        set "LANG_DIR=%%D"
    )
)
if "%LANG_DIR%"=="" (
    echo [ERROR] 找不到 Flash CS6 配置目录，请确认已安装 Flash CS6
    pause
    exit /b 1
)
echo [OK] Flash CS6 配置: %LANG_DIR%

set "COMMANDS_DIR=%LANG_DIR%\Configuration\Commands"

:: ---- 4. 写入项目路径配置 ----
:: 将 Windows 路径转换为 JSFL URI 格式: file:///C|/path/to/project
set "URI_PATH=%PROJECT_DIR:\=/%"
:: 替换盘符 C: → C|
set "URI_PATH=file:///%URI_PATH::=|%"
echo %URI_PATH%> "%COMMANDS_DIR%\flash_project_path.cfg"
echo [OK] 项目路径配置: %COMMANDS_DIR%\flash_project_path.cfg

:: ---- 5. 复制 JSFL 到 Commands 目录 ----
copy /y "%SCRIPT_DIR%\test_publish.jsfl" "%COMMANDS_DIR%\test_publish.jsfl" >nul
echo [OK] JSFL 已部署: %COMMANDS_DIR%\test_publish.jsfl

:: ---- 6. 查找 Flash.exe ----
set "FLASH_EXE="

:: 尝试常见路径（快速检查，不做全盘搜索）
for %%P in (
    "C:\Program Files\Adobe\Adobe Flash CS6\Flash.exe"
    "C:\Program Files (x86)\Adobe\Adobe Flash CS6\Flash.exe"
    "%USERPROFILE%\Downloads\adboeflash cs6(1)\Adobe Flash CS6\Flash.exe"
    "D:\qq download\adboeflash cs6(1)\Adobe Flash CS6\Flash.exe"
    "E:\flash\adboeflash cs6(1)\Adobe Flash CS6\Flash.exe"
) do (
    if exist %%P if "!FLASH_EXE!"=="" set "FLASH_EXE=%%~P"
)

:: 未找到则让用户手动输入
if "%FLASH_EXE%"=="" (
    echo [INFO] 未在常见路径找到 Flash.exe
    echo 请输入 Flash.exe 的完整路径（含文件名）:
    set /p "FLASH_EXE="
)

if "%FLASH_EXE%"=="" (
    echo [WARN] 未指定 Flash.exe，跳过计划任务创建
    goto :skip_task
)
if not exist "%FLASH_EXE%" (
    echo [WARN] 路径不存在: %FLASH_EXE%
    echo        跳过计划任务创建
    goto :skip_task
)
echo [OK] Flash.exe: %FLASH_EXE%

:: ---- 7. 生成并导入计划任务 ----
set "TASK_XML=%TEMP%\FlashCS6Task_generated.xml"
(
echo ^<?xml version="1.0" encoding="UTF-16"?^>
echo ^<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task"^>
echo   ^<RegistrationInfo^>
echo     ^<Description^>Launch Flash CS6 without UAC prompt^</Description^>
echo   ^</RegistrationInfo^>
echo   ^<Triggers /^>
echo   ^<Principals^>
echo     ^<Principal id="Author"^>
echo       ^<LogonType^>InteractiveToken^</LogonType^>
echo       ^<RunLevel^>HighestAvailable^</RunLevel^>
echo     ^</Principal^>
echo   ^</Principals^>
echo   ^<Settings^>
echo     ^<MultipleInstancesPolicy^>IgnoreNew^</MultipleInstancesPolicy^>
echo     ^<DisallowStartIfOnBatteries^>false^</DisallowStartIfOnBatteries^>
echo     ^<StopIfGoingOnBatteries^>false^</StopIfGoingOnBatteries^>
echo     ^<ExecutionTimeLimit^>PT0S^</ExecutionTimeLimit^>
echo     ^<Enabled^>true^</Enabled^>
echo   ^</Settings^>
echo   ^<Actions Context="Author"^>
echo     ^<Exec^>
echo       ^<Command^>%FLASH_EXE%^</Command^>
echo     ^</Exec^>
echo   ^</Actions^>
echo ^</Task^>
) > "%TASK_XML%"

schtasks /create /tn "FlashCS6Task" /xml "%TASK_XML%" /f >nul 2>&1
if %errorlevel%==0 (
    echo [OK] 计划任务 FlashCS6Task 已创建
) else (
    echo [WARN] 计划任务创建失败，可能需要管理员权限
    echo        请以管理员身份运行此脚本
)

:skip_task

:: ---- 8. 生成 compile_test.sh 的环境信息 ----
set "ENV_FILE=%SCRIPT_DIR%\compile_env.sh"
set "FLASH_LOG=%APPDATA%\Macromedia\Flash Player\Logs\flashlog.txt"
set "FLASH_LOG_SH=%FLASH_LOG:\=/%"
set "COMMANDS_SH=%COMMANDS_DIR:\=/%"
set "SCRIPT_DIR_SH=%SCRIPT_DIR:\=/%"

(
echo #!/bin/bash
echo # Auto-generated by setup_compile_env.bat
echo # 编译环境变量 - 由 compile_test.sh 自动 source
echo FLASH_LOG="%FLASH_LOG_SH%"
echo JSFL_PATH="%COMMANDS_SH%/test_publish.jsfl"
echo MARKER="%SCRIPT_DIR_SH%/publish_done.marker"
echo ERROR_MARKER="%SCRIPT_DIR_SH%/publish_error.marker"
echo SCRIPTS_DIR="%SCRIPT_DIR_SH%"
) > "%ENV_FILE%"
echo [OK] Shell 环境配置: %ENV_FILE%

echo.
echo ========================================
echo  配置完成！
echo ========================================
echo.
echo 使用方法：
echo   1. 启动 Flash CS6（手动或通过计划任务）
echo   2. 在 Flash 中打开 TestLoader（首次需手动）
echo   3. Agent 执行: bash scripts/compile_test.sh
echo.
pause
