"""Generate the choice-pool AS2 catalog and openable items; --check is read-only."""
import argparse
import json
import re
import shutil
import xml.etree.ElementTree as ET
from choice_reward_catalog import ROOT, load, runtime_catalog

AS2 = ROOT / 'scripts/类定义/org/flashNight/arki/item/ChoiceRewardDefinition.as'
XML = ROOT / 'data/items/消耗品_自选配给.xml'


def outputs():
    catalog = load()
    rows = runtime_catalog(catalog)
    source = '// Generated by tools/build-choice-rewards.py. Edit data/rewards/choice-rewards.json.\n'
    source += 'class org.flashNight.arki.item.ChoiceRewardDefinition {\n    public static function get():Array {\n        return [' + ','.join('pool%d()' % i for i in range(len(rows))) + '];\n    }\n'
    # Keep each generated AVM1 function below the UI16 function-body size ceiling.
    for i, row in enumerate(rows):
        literal = json.dumps(row, ensure_ascii=False, indent=4)
        literal = re.sub(r'"([A-Za-z_][A-Za-z0-9_]*)"(?=\s*:)', r'\1', literal)
        source += '    private static function pool%d():Object {\n        return %s;\n    }\n' % (i, literal)
    source += '}\n'
    root = ET.Element('root')
    root.append(ET.Comment(' Generated by tools/build-choice-rewards.py; edit data/rewards/choice-rewards.json. '))
    for pool in catalog['pools']:
        item = ET.SubElement(root, 'item')
        candidate_count = sum(group['draw'] for group in pool['groups'])
        for key, value in [('name', pool['itemName']), ('displayname', pool['itemName']), ('icon', '材料盒子'),
                           ('type', '消耗品'), ('use', '礼包'), ('price', '0'),
                           ('description', f'打开后随机展示{candidate_count}套配给，自选一套。候选保留，可稍后从装备界面的自选礼包继续选择；技能直接授予；物品到暂存领取，插件需自行安装。付费卡确认时扣除显示的K点。')]:
            ET.SubElement(item, key).text = value
        data = ET.SubElement(item, 'data')
        ET.SubElement(data, 'level').text = '0'; ET.SubElement(data, 'weight').text = '0'
        pack = ET.SubElement(data, 'rewardPack')
        ET.SubElement(pack, 'mode').text = 'playerChoice'; ET.SubElement(pack, 'poolId').text = pool['id']
    ET.indent(root, space='    ')
    return {AS2:b'\xef\xbb\xbf'+source.replace('\n','\r\n').encode('utf-8'),
            XML:ET.tostring(root, encoding='utf-8', xml_declaration=True)+b'\n'}


def main():
    parser = argparse.ArgumentParser(__doc__); parser.add_argument('--check', action='store_true')
    check = parser.parse_args().check
    for path, content in outputs().items():
        if check:
            if not path.exists() or path.read_bytes() != content: raise ValueError(str(path)+' is stale')
        else:
            if path == AS2 and not path.exists(): shutil.copyfile(ROOT/'scripts/类定义/org/flashNight/arki/scene/BookDefinition.as', path)
            path.write_bytes(content)
    print('choice rewards: catalog and item projection verified')


if __name__ == '__main__': main()
