"""Validate editable book data and generate its AS2 definition. --check is read-only."""
import argparse
import json
import re
from pathlib import Path
import shutil
import xml.etree.ElementTree as ET
from choice_reward_catalog import resolve_book_choices, validate_loadout

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'data/books/repair-campus.json'
OUTPUT = ROOT / 'scripts/类定义/org/flashNight/arki/scene/BookDefinition.as'
PACK_OUTPUT = ROOT / 'data/items/消耗品_书中配给.xml'
RECIPE_OUTPUT = ROOT / 'data/crafting/书中配给.json'


def load_mods():
    directory = ROOT / 'data/items/equipment_mods'
    return {mod.findtext('name'): mod
            for entry in ET.parse(directory / 'list.xml').findall('items')
            for mod in ET.parse(directory / entry.text).findall('mod')}


def validate_choices(data, items):
    """Validate complete starter sets, not merely the existence of each component."""
    mods = load_mods()
    choices = data['buildChoices']
    if not isinstance(choices, list) or [c['afterMap'] for c in choices] != [1, 3]:
        raise ValueError('build choices must follow maps two and four')
    names = [data['ammoBundle']['name']]
    for checkpoint in choices:
        names.append(checkpoint['voucher'])
        bounded_integer(checkpoint['levelCeiling'], 1, 15, 'choice level ceiling')
        if len(checkpoint['options']) != 4:
            raise ValueError('each voucher must offer four loadouts')
        uses = set()
        for option in checkpoint['options']:
            names.append(option['name'])
            weapon = items.get(option['weapon'])
            if (weapon is None or weapon.findtext('type') != '武器'
                    or option['weapon'] not in data['equipment']
                    or not 1 <= int(weapon.findtext('data/level', '999')) <= checkpoint['levelCeiling']):
                raise ValueError('choice weapon must be usable at its checkpoint')
            uses.add(weapon.findtext('use'))
            validate_loadout(option, checkpoint['levelCeiling'], items, mods)
        if '刀' not in uses or not uses & {'手枪', '长枪'}:
            raise ValueError('each checkpoint must retain melee and gun pivots')
    if len(names) != len(set(names)) or any(not n.startswith('书中') for n in names):
        raise ValueError('book delivery identities must be unique and scoped')
    supply = data['ammoBundle']['contents']
    required_ammo = {items[n].findtext('data/clipname') for n in data['equipment']
                     if n in items} - {None, ''}
    actual_ammo = set()
    for entry in supply:
        meta = items.get(entry['name'])
        if meta is None or meta.findtext('use') != '弹夹':
            raise ValueError('ammo bundle must only contain ammunition')
        bounded_integer(entry['count'], 1, 30, 'ammo bundle count')
        if entry['name'] in actual_ammo: raise ValueError('duplicate ammo bundle entry')
        actual_ammo.add(entry['name'])
    if not required_ammo <= actual_ammo:
        raise ValueError('recurring ammunition must cover all book weapons')


def generated_deliveries(data):
    """Pure data: finite vouchers -> ordinary crafting -> durable fixed reward packs."""
    root = ET.Element('root')
    root.append(ET.Comment(' Generated by tools/build-book-definition.py; edit data/books/repair-campus.json. '))
    recipes = []

    def item(name, kind, use, icon, description):
        element = ET.SubElement(root, 'item')
        for key, value in [('name', name), ('displayname', name), ('icon', icon),
                           ('type', kind), ('use', use), ('price', '0'), ('description', description)]:
            ET.SubElement(element, key).text = value
        return element

    def pack(name, description, entries):
        element = item(name, '消耗品', '礼包', '材料盒子', description + ' 打开后在待领取中领取；插件需自行安装。仅供本次书中历险使用。')
        detail = ET.SubElement(element, 'data')
        ET.SubElement(detail, 'level').text = '0'
        ET.SubElement(detail, 'weight').text = '0'
        reward = ET.SubElement(detail, 'rewardPack')
        ET.SubElement(reward, 'mode').text = 'fixed'
        output = ET.SubElement(reward, 'entries')
        for name, count in entries:
            entry = ET.SubElement(output, 'entry')
            for key, value in [('itemName', name), ('quantityMin', count), ('quantityMax', count)]:
                ET.SubElement(entry, key).text = str(value)

    for checkpoint in data['buildChoices']:
        voucher = checkpoint['voucher']
        item(voucher, '收集品', '材料', '强化石', '从装备菜单进入材料，选中本凭证前往合成，在“书中配给”分类兑换一套配给包。每张凭证四选一，兑换后打开包并领取装备、插件和补给。仅供本次书中历险使用。')
        for option in checkpoint['options']:
            entries = [(option['weapon'], 1)] + [(n, 1) for n in option['mods']]
            entries += [(entry['name'], entry['count']) for entry in option['consumables']]
            pack(option['name'], option['description'], entries)
            recipes.append(dict(recipeId='craft.book-supply.%03d' % (len(recipes) + 1),
                                title=option['title'], name=option['name'], value=1,
                                price=0, kprice=0, materials=[voucher + '#1']))
    pack(data['ammoBundle']['name'], '内含' + '、'.join(entry['name'] + '×' + str(entry['count']) for entry in data['ammoBundle']['contents']) + '。',
         [(entry['name'], entry['count']) for entry in data['ammoBundle']['contents']])
    ET.indent(root, space='    ')
    xml = b'<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(root, encoding='utf-8') + b'\n'
    return {PACK_OUTPUT: xml, RECIPE_OUTPUT: (json.dumps(recipes, ensure_ascii=False, indent=2) + '\n').encode('utf-8')}


def validate_boss(data, units, items):
    c = data['bossEncounter']
    if set(c) != {'mapIndex','instanceName','intervalFrames','maxAlive','maxRanged','groups','rangedTypes','supplies'}:
        raise ValueError('invalid boss encounter fields')
    if c['mapIndex'] != len(data['maps']) - 1 or c['instanceName'] != 'bookCampusTeacher':
        raise ValueError('boss must own final map')
    final_map = data['maps'][c['mapIndex']]
    if final_map['waves'] != 1 or final_map['count'] != [1,1] or len(final_map['enemies']) != 1:
        raise ValueError('boss encounter requires one unambiguous boss actor')
    bounded_integer(c['intervalFrames'], 60, 300, 'reinforcement interval')
    bounded_integer(c['maxAlive'], 1, 3, 'reinforcement live cap')
    bounded_integer(c['maxRanged'], 1, c['maxAlive'], 'ranged live cap')
    if len(c['groups']) != 3 or len(c['supplies']) != 4: raise ValueError('finite three-phase boss required')
    seen, previous, count = set(), 1, 0
    for group in c['groups']:
        if set(group) != {'hpRatio','level','pools'}: raise ValueError('invalid reinforcement group')
        ratio = group['hpRatio']
        if type(ratio) not in (float,int) or not 0 < ratio < previous: raise ValueError('descending HP phases required')
        previous = ratio
        bounded_integer(group['level'], 1, 15, 'reinforcement level')
        if not 1 <= len(group['pools']) <= 4: raise ValueError('oversized group')
        for pool in group['pools']:
            if not isinstance(pool,list) or not 1 <= len(pool) <= 4: raise ValueError('invalid enemy pool')
            for enemy in pool:
                if type(enemy) is not int or enemy not in units or enemy in seen: raise ValueError('duplicate or unknown reinforcement')
                seen.add(enemy)
            count += 1
    if count > 8 or set(c['rangedTypes']) - seen: raise ValueError('invalid reinforcement budget')
    for supply in c['supplies']:
        if set(supply) != {'name','count'} or supply['name'] not in items: raise ValueError('invalid reinforcement supply')
        bounded_integer(supply['count'], 1, 3, 'reinforcement supply count')
        if supply['name'] != data['ammoBundle']['name'] and items[supply['name']].findtext('use') not in ('药剂','手雷','战场补给'):
            raise ValueError('reinforcements only grant tactical supplies')


def bounded_integer(value, low, high, label):
    if type(value) is not int or not low <= value <= high:
        raise ValueError('invalid ' + label)


def validate_skills(data, skills):
    bounded_integer(data['skillMaxUnlockLevel'], 1, 15, 'book skill level ceiling')
    eligible = {s.findtext('Name') for s in skills if s.findtext('Name')
                and s.findtext('Type') and int(s.findtext('MaxLevel', '0')) > 0
                and 1 <= int(s.findtext('UnlockLevel', '999')) <= data['skillMaxUnlockLevel']}
    selected = data['skills']
    if (not isinstance(selected, list) or not selected
            or any(type(name) is not str for name in selected)
            or len(selected) != len(set(selected)) or not set(selected) <= eligible):
        raise ValueError('book skills must be a nonempty unique selection of learnable skills within the level ceiling')


def validate_medicine(name, items, stat):
    if name not in items or items[name].findtext('use') != '药剂':
        raise ValueError('map medicine must be a storable potion')
    if not any(e.get('type') == 'heal' and e.get('target') == 'self'
               and float(e.get(stat, '0').rstrip('%')) > 0
               for e in items[name].findall('data/effects/effect')):
        raise ValueError('map medicine must restore ' + stat)


def validate_loot(data, items):
    bounded_integer(data['startingMoney'], 0, 100000, 'starting money')
    bounded_integer(data['startingSkillPoints'], 0, 200, 'starting skill points')
    loot = data['loot']
    for key in ('equipmentChance', 'supplyChance'):
        bounded_integer(loot[key], 0, 100, key)
    # Enemy drops look up the canonical item name before creating a pickup.
    # Display aliases such as 金钱 / 经验 silently disappear in that consumer.
    if (loot['moneyItem'] != '金币' or loot['experienceItem'] != '经验值'
            or loot['skillPointItem'] != '技能点'):
        raise ValueError('currency drops require canonical item names')
    for key in ('moneyItem', 'experienceItem', 'skillPointItem', 'medicalItem'):
        if loot[key] not in items:
            raise ValueError('unknown loot item ' + loot[key])
    medical = items[loot['medicalItem']]
    if medical.findtext('use') != '战场补给' or not any(
            e.get('type') == 'heal' and e.get('target') == 'self'
            and e.get('hp', '').endswith('%') and float(e.get('hp')[:-1]) > 0
            for e in medical.findall('data/effects/effect')):
        raise ValueError('medical pickup must restore a proportion of health')
    bounded_integer(loot['healingCount'], 1, 20, 'healing count')
    bounded_integer(loot['armorWaves'], 1, 2, 'armor waves')
    support = loot['support']
    if not isinstance(support, list) or not 1 <= len(support) <= 8:
        raise ValueError('invalid support cycle')
    for entry in support:
        bundle = entry['kind'] == 'ammo' and entry['name'] == data['ammoBundle']['name'] and entry['count'] == 1
        if entry['name'] not in items or (not bundle and items[entry['name']].findtext('use') not in ('药剂', '弹夹', '手雷')):
            raise ValueError('support must be an existing potion, ammunition or grenade')
        bounded_integer(entry['count'], 1, 20, 'support count')
        if entry['kind'] not in ('mana', 'ammo', 'grenade'):
            raise ValueError('invalid support kind')
    if sum(entry['kind'] == 'mana' for entry in support) != 1:
        raise ValueError('support cycle needs exactly one mana entry')
    mod_dir = ROOT / 'data/items/equipment_mods'
    mods = {mod.findtext('name'): mod
            for entry in ET.parse(mod_dir / 'list.xml').findall('items')
            for mod in ET.parse(mod_dir / entry.text).findall('mod')}
    tier_system = ET.parse(ROOT / 'data/equipment/equipment_config.xml').find('EquipmentConfig/TierSystem')
    tiers = {entry.get('material'): entry for entry in tier_system.findall('TierMapping')}
    available_equipment = set()
    for stage in data['maps']:
        pool = stage['equipment']
        if not isinstance(pool, list) or not pool or any(name not in data['equipment'] for name in pool):
            raise ValueError('invalid map equipment pool')
        armor = stage['armor']
        if (not isinstance(armor, list) or len(armor) < loot['armorWaves']
                or len(armor) != len(set(armor)) or any(
                    name not in data['equipment'] or name not in items
                    or items[name].findtext('type') != '防具'
                    or not 1 <= int(items[name].findtext('data/level', '999')) <= 15 for name in armor)):
            raise ValueError('map armor pool must contain distinct registered armor')
        if set(armor) & set(pool):
            raise ValueError('armor and weapon choices need independent drop slots')
        validate_medicine(stage['healingItem'], items, 'hp')
        validate_medicine(stage['manaItem'], items, 'mp')
        bounded_integer(stage['waves'], 1, 10, 'wave count')
        bounded_integer(stage['skillPoints'], 0, 100, 'map skill point budget')
        available_equipment.update(pool + armor)
        materials = stage['materials']
        if not isinstance(materials, list) or len(materials) > stage['waves']:
            raise ValueError('materials allow at most one stack per wave')
        for entry in materials:
            name = entry['name']
            if name not in items or items[name].findtext('use') != '材料':
                raise ValueError('growth pickup must be a registered material')
            bounded_integer(entry['count'], 1, 100, 'material stack count')
            if name in mods:
                uses = set(mods[name].findtext('use', '').split(','))
                if not any(items[n].findtext('use') in uses for n in available_equipment):
                    raise ValueError('mod has no matching equipment in reached map pools')
            elif name in tiers:
                tier = tiers[name]
                default = tier_system.find("DefaultTierData/Tier[@name='" + tier.get('name') + "']")
                eligible = False
                for n in available_equipment:
                    item = items[n]
                    target = item.find(tier.get('key'))
                    if target is None and item.findtext('type') == '防具' and item.findtext('use') != '颈部装备' and int(item.findtext('data/level', '999')) < 10:
                        target = default
                    if target is not None and 1 <= int(target.findtext('level', '999')) <= data['skillMaxUnlockLevel']:
                        eligible = True
                if not eligible:
                    raise ValueError('tier material has no usable upgrade within book level ceiling')
            elif name != '强化石':
                raise ValueError('growth material must support equipment tuning')
        bounded_integer(stage['experience'], 1, 1000000, 'map experience budget')
        money = stage['money']
        if not isinstance(money, list) or len(money) != 2:
            raise ValueError('invalid money range')
        bounded_integer(money[0], 1, 100000, 'minimum money')
        bounded_integer(money[1], money[0], 100000, 'maximum money')


def main():
    parser = argparse.ArgumentParser(__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = resolve_book_choices(json.loads(SOURCE.read_text(encoding='utf-8')))
    if data['schema'] != 'playable-book.v1' or data['id'] != 'repair-campus':
        raise ValueError('unsupported book identity')
    if any(type(data[k]) is not int or not 0 <= data[k] <= 100 for k in ('regularSp', 'firstClearSp', 'recordSpPerTier')):
        raise ValueError('invalid SP configuration')
    if data['recordMinutes'] != sorted(set(data['recordMinutes']), reverse=True) or not all(type(v) is int and 1 <= v <= 60 for v in data['recordMinutes']):
        raise ValueError('record tiers must be finite descending minutes')
    validate_skills(data, ET.parse(ROOT / 'data/skills/skills.xml').findall('Skill'))
    units = {u['id'] for u in json.loads((ROOT / 'data/units/units.json').read_text(encoding='utf-8-sig'))}
    items = {}
    for path in (ROOT / 'data/items').glob('*.xml'):
        if path == PACK_OUTPUT: continue
        items.update((item.findtext('name'), item) for item in ET.parse(path).findall('.//item'))
    validate_choices(data, items)
    outputs = generated_deliveries(data)
    items.update((item.findtext('name'), item) for item in ET.fromstring(outputs[PACK_OUTPUT]).findall('item'))
    if not 6 <= len(data['maps']) <= 8:
        raise ValueError('book requires 6-8 maps')
    for stage in data['maps']:
        if not (ROOT / 'flashswf/backgrounds' / stage['background']).is_file():
            raise ValueError('missing background ' + stage['background'])
        if any(enemy not in units for enemy in stage['enemies']):
            raise ValueError('unknown enemy')
        if not 1 <= stage['level'][0] <= stage['level'][1] <= 60:
            raise ValueError('invalid levels')
        if not 1 <= stage['count'][0] <= stage['count'][1] <= 8:
            raise ValueError('invalid spawn count')
    missing = set(data['equipment'] + data['supplies']) - items.keys()
    if missing:
        raise ValueError('unknown items: ' + ', '.join(sorted(missing)))
    validate_loot(data, items)
    validate_boss(data, units, items)
    literal = json.dumps(data, ensure_ascii=False, indent=4)
    # AS2 object literals require identifier keys, unlike JSON / JavaScript.
    literal = re.sub(r'"([A-Za-z_][A-Za-z0-9_]*)"(?=\s*:)', r'\1', literal)
    text = '// Generated by tools/build-book-definition.py from data/books/repair-campus.json.\n'
    text += 'class org.flashNight.arki.scene.BookDefinition {\n    public static function get():Object {\n        return ' + literal + ';\n    }\n}\n'
    content = b'\xef\xbb\xbf' + text.replace('\n', '\r\n').encode('utf-8')
    outputs[OUTPUT] = content
    for path, content in outputs.items():
        if args.check:
            if not path.is_file() or path.read_bytes() != content:
                raise ValueError(str(path.relative_to(ROOT)) + ' is stale')
        else:
            if path == OUTPUT and not path.exists():
                shutil.copyfile(ROOT / 'scripts/类定义/org/flashNight/arki/scene/StageReturnFlow.as', OUTPUT)
            path.write_bytes(content)
    print('book definition: 7 maps, 8 finite loadouts and matching ammo verified')


if __name__ == '__main__':
    main()
