"""Extract the two original book timelines without changing their source SWF.

Requires the repository's FFDec. --check compares every generated byte/hash.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import tempfile
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'flashswf/UI/书架界面.swf'
OUTPUT = ROOT / 'launcher/web/assets/bookshelf'
BOOKS = [('dust', 44, '尘都诡谈'), ('babylon', 55, '光明巴比伦')]


def digest(data):
    return hashlib.sha256(data).hexdigest()


def reader_page(data):
    """Keep original paper/text vectors; retire the original Flash paging controls."""
    ET.register_namespace('', 'http://www.w3.org/2000/svg')
    ET.register_namespace('xlink', 'http://www.w3.org/1999/xlink')
    ET.register_namespace('ffdec', 'https://www.free-decompiler.com/flash')
    root = ET.fromstring(data)
    group = root.find('{http://www.w3.org/2000/svg}g')
    transform = [float(x) for x in re.findall(r'-?\d+(?:\.\d+)?', group.attrib['transform'])]
    if len(transform) != 6 or transform[:4] != [1, 0, 0, 1]:
        raise ValueError('unexpected original book transform')
    # Source paper is 281 x 421; both paging buttons lie below its lower edge.
    root.set('viewBox', f'{transform[4] - 0.5:g} 0 281 421')
    root.set('width', '281px'); root.set('height', '421px')
    for node in list(group):
        if node.attrib.get('{https://www.free-decompiler.com/flash}characterId') in ('20', '24'):
            group.remove(node)
    return ET.tostring(root, encoding='utf-8', xml_declaration=True) + b'\n'


def main():
    parser = argparse.ArgumentParser(__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    artifacts = {}
    with tempfile.TemporaryDirectory(prefix='cf7-books-') as temp:
        subprocess.run([str(ROOT / 'tools/ffdec/ffdec-cli.exe'), '-format', 'sprite:svg',
                        '-selectid', '44,55', '-export', 'sprite', temp, str(SOURCE)],
                       check=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        for book, symbol, title in BOOKS:
            folder = Path(temp) / f'DefineSprite_{symbol}_{title}'
            pages = sorted(folder.glob('*.svg'), key=lambda p: int(p.stem))
            if len(pages) != 15:
                raise ValueError(f'{title}: expected 15 original pages, got {len(pages)}')
            for page in pages:
                artifacts[f'{book}/{int(page.stem):02}.svg'] = reader_page(page.read_bytes())
    manifest = {'schema': 'bookshelf-pages.v1', 'source': SOURCE.relative_to(ROOT).as_posix(),
                'sourceSha256': digest(SOURCE.read_bytes()), 'generator': 'FFDec 21.1.1 sprite:svg + tools/build-bookshelf-pages.py reader viewport',
                'books': [{'id': b, 'title': t, 'symbol': s, 'pages': 15} for b, s, t in BOOKS],
                'totalBytes': sum(map(len, artifacts.values())),
                'files': {name: {'sha256': digest(data), 'bytes': len(data)} for name, data in artifacts.items()}}
    artifacts['manifest.json'] = (json.dumps(manifest, ensure_ascii=False, indent=2) + '\n').encode('utf-8')
    for name, data in artifacts.items():
        path = OUTPUT / name
        if args.check:
            if not path.is_file() or path.read_bytes() != data:
                raise ValueError(f'generated book asset differs: {name}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    print(f'bookshelf pages: 30 pages, {manifest["totalBytes"]} bytes, ' + ('verified' if args.check else 'generated'))


if __name__ == '__main__':
    main()
