"""从睡眠 XFL 派生日月表盘与卡片边饰；--check 只读核对完整闭包。"""
import argparse
import hashlib
import importlib.util
import json
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
LIB = ROOT / "flashswf/UI/睡觉界面/LIBRARY"
OUTPUT = ROOT / "launcher/web/assets/sleep"
ENGINE = ROOT / "tools/xfl-ui-svg/xfl_to_svg.py"
PALETTE = ROOT / "launcher/web/css/sleep/tokens.css"
RECIPES = {
    "day-face.svg": ("金色太阳", None),
    # 原夜晚卡片的上部日月插画；裁切保留月亮脸与环绕星轨，不带文字。
    "night-face.svg": ("夜晚选项", (210, 135, 640, 640)),
    "day-card.svg": ("清晨选项", None),
    "night-card.svg": ("夜晚选项", None),
}


def digest(data):
    return hashlib.sha256(data).hexdigest()


def generate():
    spec = importlib.util.spec_from_file_location("sleep_xfl_svg", ENGINE)
    engine = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(engine)
    outputs, sources, recipes = {}, set(), {}
    for name, (symbol, crop) in RECIPES.items():
        renderer, svg, _ = engine.export(LIB, symbol, 0, (1200, 1600), OUTPUT, [], {})
        if renderer.unsupported or renderer.skipped:
            raise RuntimeError(f"{symbol}: unsupported/skipped art: {renderer.unsupported} {renderer.skipped}")
        bounds = renderer.symbol_bbox(symbol)
        view = crop or (bounds[0], bounds[1], bounds[2] - bounds[0], bounds[3] - bounds[1])
        attrs = 'viewBox="%s" width="%g" height="%g"' % (" ".join("%g" % n for n in view), view[2], view[3])
        svg = re.sub(r'viewBox="[^"]+"\s+width="[^"]+"\s+height="[^"]+"', attrs, svg, count=1)
        outputs[name] = svg.encode("utf-8")
        sources.update(renderer.sources)
        recipes[name] = {"symbol": symbol, "frame": 0, "viewBox": list(view), "textFieldsExcluded": len(renderer.fields)}
    colors = {}
    for key, value in re.findall(r"--sleep-([a-z-]+):\s*#([0-9a-fA-F]{3,6});", PALETTE.read_text(encoding="utf-8")):
        if len(value) == 3:
            value = "".join(c * 2 for c in value)
        colors[key] = [int(value[i:i+2], 16) for i in (0, 2, 4)]
    palette = json.dumps({"v": 1, "colors": colors}, ensure_ascii=False, separators=(",", ":"))
    outputs["palette.js"] = ("/* Generated by tools/export-sleep-art.py from sleep/tokens.css. */\n"
        + "(function(root){var palette=" + palette + ";"
        + "if(typeof module!=='undefined'&&module.exports)module.exports=palette;"
        + "if(root)root.SleepArtPalette=palette;})(typeof window!=='undefined'?window:null);\n").encode("utf-8")
    sources.update([ENGINE, PALETTE, Path(__file__).resolve()])
    manifest = {
        "version": 1,
        "authority": "flashswf/UI/睡觉界面/LIBRARY",
        "generator": "tools/export-sleep-art.py",
        "sourceHashEncoding": "utf8-lf",
        "sources": {Path(p).relative_to(ROOT).as_posix(): digest(Path(p).read_bytes().replace(b"\r\n", b"\n")) for p in sorted(sources, key=str)},
        "recipes": recipes,
        "files": {name: {"sha256": digest(data), "bytes": len(data)} for name, data in outputs.items()},
    }
    outputs["manifest.json"] = (json.dumps(manifest, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        actual = {p.name for p in OUTPUT.iterdir() if p.is_file()} if OUTPUT.exists() else set()
        if actual != set(expected) or any((OUTPUT / name).read_bytes() != data for name, data in expected.items()):
            raise SystemExit("sleep art closure is stale; run python tools/export-sleep-art.py")
    else:
        OUTPUT.mkdir(parents=True, exist_ok=True)
        for name, data in expected.items():
            (OUTPUT / name).write_bytes(data)
    print(f"Sleep art {'verified' if args.check else 'exported'}: {len(expected)} files, {sum(map(len, expected.values()))} bytes")


if __name__ == "__main__":
    main()
