"""Import the reviewed R8-I1-H1 headquarters visual assets; gameplay data stays authoritative."""
import argparse,hashlib,json,zipfile
from lib.blackiron_presentation import build_config
from lib.stage_camera_presets import apply_preset, check_preset, preset_manifest, refresh_preset
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DEST=ROOT/'launcher/web/assets/stage-diorama/blackiron-hq'
DATA=ROOT/'launcher/web/modules/stage-select/stage-select-blackiron-data.js'
ZIP_HASH='5f6096e4807a35d37e96a80a81e3ba60598bf9f507a38efa24e0f18116afaee9'
def sha(b):return hashlib.sha256(b).hexdigest()
def generate(archive):
 assert sha(archive.read_bytes())==ZIP_HASH,'Unreviewed handoff archive'
 output={}
 with zipfile.ZipFile(archive) as z:
  prefix='blackiron-hq-r8-i1-h1/工程/'
  read=lambda p:z.read(prefix+p)
  interaction=json.loads(read('interaction.json'));views=json.loads(read('views.json'))
  for source,target in [('model/full/blackiron-hq-r8.glb','headquarters.glb'),('model/selection.glb','selection.glb'),('assets/fallback-overview.jpg','fallback.jpg'),('interaction.json','interaction.json'),('style.json','style.json'),('views.json','views.json')]:output[DEST/target]=read(source)
  # Share the existing r180 core/loader. Only postprocessing modules are added.
  vp=prefix+'review/vendor/three/examples/jsm/'
  for n in z.namelist():
   if n.startswith(vp) and any(n[len(vp):].startswith(p) for p in ['postprocessing/','shaders/']):
    text=z.read(n).decode().replace("from 'three'","from '../../../base-gate/vendor/three.module.js'")
    output[DEST/'vendor'/n[len(vp):]]=text.encode()
  output[DEST/'vendor/LICENSE']=read('review/vendor/three/LICENSE')
  config=build_config(interaction,views)
  apply_preset(config,'hq')
  output[DATA]=('// Generated by tools/import-blackiron-diorama.py. Visual data only; IDs unchanged.\nvar StageSelectBlackironData = '+json.dumps(config,ensure_ascii=False,indent=2)+';\n').encode()
  manifest={'schema':1,'sourceZipSha256':ZIP_HASH,'revision':'R8-I1-H1','changes':'GLBs unchanged; native display order follows mainline; r180 postprocessing imports share existing core. Demo gameplay state excluded.','files':[{'path':p.relative_to(ROOT).as_posix(),'bytes':len(b),'sha256':sha(b)} for p,b in output.items()]}
  manifest['cameraPreset']=preset_manifest('hq')
  output[DEST/'manifest.json']=(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n').encode()
 return output
def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('archive',nargs='?',type=Path);p.add_argument('--check',action='store_true');p.add_argument('--refresh-camera',action='store_true',help='Regenerate camera/labels on the verified imported assets');a=p.parse_args()
 if a.refresh_camera:refresh_preset(DATA,DEST,'hq')
 if a.check:
  m=json.loads((DEST/'manifest.json').read_text(encoding='utf-8'));total=0
  check_preset(DATA,m,'hq')
  for r in m['files']:
   b=(ROOT/r['path']).read_bytes();assert len(b)==r['bytes'] and sha(b)==r['sha256'],r['path'];total+=len(b)
  assert total<9_000_000,'Headquarters visual bundle budget exceeded'
  print(json.dumps({'ok':True,'files':len(m['files']),'bytes':total}));return
 if a.refresh_camera:return
 if not a.archive:p.error('archive required')
 for path,data in generate(a.archive).items():path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(data)
 print('Headquarters visual bundle imported')
if __name__=='__main__':main()
