using System;using System.Collections.Generic;using Newtonsoft.Json.Linq;using Xunit;using CF7Launcher.Tasks;
namespace CF7Launcher.Tests.Tasks {
 public class BookComicTaskTests {
  static JObject Data(string id="bookcomic:1")=>new JObject{["v"]=1,["presentationId"]=id,["slot"]="bookrun_test",["sceneId"]="scene:1",["pageId"]="prologue"};
  static JObject Web(string cmd,string call,JObject data,string instance="panel:1")=>new JObject{["panel"]="book-comic",["domain"]="book-comic",["cmd"]=cmd,["callId"]=call,["panelInstanceId"]=instance,["payload"]=data};
  static JObject Reply(JObject sent,string phase,string op){var r=(JObject)sent.DeepClone();r["operation"]=op;r["success"]=true;r["phase"]=phase;r["error"]="";return r;}
  [Fact]public void ExactPrepareFinishAndDuplicateAreBound(){var sent=new List<JObject>();var closed=new List<string>();using var t=new BookComicTask(()=>true,s=>{sent.Add(JObject.Parse(s.TrimEnd('\0')));return true;});t.SetPostToWeb(s=>{},null,closed.Add);var d=Data();Assert.True(t.Reserve(d));Assert.True(t.Bind("panel:1",d.ToString()));t.HandleWebRequest("prepared",Web("prepared","w1",d));Assert.Equal("bookComicPrepared",sent[0].Value<string>("action"));t.HandleFlashResponse(Reply(sent[0],"presenting","prepared"),null);t.HandleWebRequest("continue",Web("continue","w2",d));t.HandleWebRequest("continue",Web("continue","w2",d));Assert.Equal(2,sent.Count);t.HandleFlashResponse(Reply(sent[1],"finished","finish"),null);Assert.Single(closed);t.OnHostClosed("panel:1");Assert.Equal(2,sent.Count);Assert.False(t.Reserve(d));}
  [Fact]public void RealAs2TaskEnvelopeUnwrapsResponse(){var sent=new List<JObject>();var posts=new List<string>();using var t=new BookComicTask(()=>true,s=>{sent.Add(JObject.Parse(s.TrimEnd('\0')));return true;});t.SetPostToWeb(posts.Add,null,s=>{});var d=Data();t.Reserve(d);t.Bind("panel:1",d.ToString());t.HandleWebRequest("prepared",Web("prepared","w1",d));t.HandleFlashResponse(new JObject{["task"]="book_comic_response",["payload"]=Reply(sent[0],"presenting","prepared")},null);Assert.Single(posts);Assert.True(JObject.Parse(posts[0]).Value<bool>("success"));var expired=Reply(d,"expired","finish");expired["callId"]=0;expired["panelInstanceId"]="";t.HandleFlashResponse(new JObject{["task"]="book_comic_response",["payload"]=expired},null);Assert.False(t.CanOpen(d.ToString()));}
  [Fact]public void ExpiredBeforeOpenLeavesTombstone(){using var t=new BookComicTask(()=>true,s=>true);var d=Data();var r=Reply(d,"expired","finish");r["callId"]=0;r["panelInstanceId"]="";t.HandleFlashResponse(r,null);Assert.False(t.Reserve(d));}
  [Fact]public void ExpiredQueuedOpenCannotBind(){var closed=new List<string>();using var t=new BookComicTask(()=>true,s=>true);t.SetPostToWeb(s=>{},null,closed.Add);var d=Data();Assert.True(t.Reserve(d));var r=Reply(d,"expired","finish");r["callId"]=0;r["panelInstanceId"]="";t.HandleFlashResponse(r,null);Assert.False(t.CanOpen(d.ToString()));Assert.False(t.Bind("panel:1",d.ToString()));Assert.Empty(closed);}
  [Fact]public void ForeignInstanceAndStaleTerminalCannotCloseNewPage(){var sent=new List<JObject>();var closed=new List<string>();using var t=new BookComicTask(()=>true,s=>{sent.Add(JObject.Parse(s.TrimEnd('\0')));return true;});t.SetPostToWeb(s=>{},null,closed.Add);var d=Data();t.Reserve(d);t.Bind("panel:1",d.ToString());t.HandleWebRequest("skip",Web("skip","w1",d,"foreign"));Assert.Empty(sent);t.HandleWebRequest("skip",Web("skip","w2",d));var late=Reply(sent[0],"finished","finish");t.OnDisconnected();var d2=Data("bookcomic:2");Assert.True(t.Reserve(d2));Assert.True(t.Bind("panel:2",d2.ToString()));t.HandleFlashResponse(late,null);Assert.Single(closed);Assert.True(t.CanOpen(d2.ToString()));}
  [Fact]public void GenericWebTaskBridgeCannotForgeComicAuthority(){Assert.False(CF7Launcher.Guardian.WebOverlayForm.IsWebTaskRouterIngressAllowed("book_comic_response"));Assert.False(CF7Launcher.Guardian.WebOverlayForm.IsWebTaskRouterIngressAllowed("panel_request"));}
  [Fact]public void OpenDataRejectsUnknownPageAndFields(){var d=Data();Assert.NotNull(BookComicTask.BuildOpenData("book_chapter",d.ToString()));d["pageId"]="other";Assert.Null(BookComicTask.BuildOpenData("book_chapter",d.ToString()));d["pageId"]="boss";d["action"]="anything";Assert.Null(BookComicTask.BuildOpenData("book_chapter",d.ToString()));}
 }
}
